### ISSUE TITLE
opc ua client Alarm and condition

### ISSUE THREAD

**Issue by yashvanthb** [FreeOpcUa/python-opcua#1019]
Need Help please
Hi can any one describe the what is alarm and condition in opc ua and why to subscribe to events
1. What data will i get from alarm when i subscribe is their any event-Filter is need

can any one explain why used and purpose of it
1. get_child 
2. SubHandler()
3. will subscribe_events() function will subscribe to  particular events/condition of changes that  my occur in future.
4. subscribe_data_change function
5.At a time how many events can i fetch is their any limitation
obj = root.get_child(["0:Objects", "2:MyObject"])
        print("MyObject is: ", obj)

        myevent = root.get_child(["0:Types", "0:EventTypes", "0:BaseEventType", "2:MyFirstEvent"])
        print("MyFirstEventType is: ", myevent)

        msclt = SubHandler()
        sub = client.create_subscription(100, msclt)
        handle = sub.subscribe_events(obj, myevent)

**Comment by AndreasHeine** [comment]
https://documentation.unified-automation.com/uasdkhp/1.0.0/html/_doc__opc_ua__alarms_and_conditions.html

**Comment by zerox1212** [comment]
Sorry, but the purpose of Issues is to fix specific problems with the code. If you post an example of what you have tried on your own we can take a look, however asking open ended questions isn't going to get many answers here.
