### ISSUE TITLE
To list the namespaceUri

### ISSUE THREAD

**Issue by yashvanthb** [FreeOpcUa/python-opcua#1024]
Hi is their any function in client side to list the namespaceUri like gives the available number of namespaceURI  

http://opcfoundation.org/UA/
urn:LAPTOP-0OJQ2QSC:UnifiedAutomation:UaServerCpp
urn:UnifiedAutomation:CppDemoServer:UANodeSetXmlImport

**Comment by AndreasHeine** [comment]
get_namespace_array()

**Comment by yashvanthb** [comment]
i need in number

**Comment by AndreasHeine** [comment]
then number = client.get_namespace_index(uri)

**Comment by AndreasHeine** [comment]
please check: https://github.com/FreeOpcUa/python-opcua/tree/master/examples

**Comment by yashvanthb** [comment]
thanks for quick replay how to separate the URI using get_namespace_array like if is has 
i am new to opc ua don't mind if asking too many questions

http://opcfoundation.org/UA/
urn:LAPTOP-0OJQ2QSC:UnifiedAutomation:UaServerCpp
urn:UnifiedAutomation:CppDemoServer:UANodeSetXmlImport
like i need in single varibles

**Comment by AndreasHeine** [comment]
len(array)

but this is not relatet to python opc ua...

**Comment by yashvanthb** [comment]
Thanks AndreasHeine
