### ISSUE TITLE
Release 0.98.10 BadCommunicationError, reason:Chunk size (132) exceeded maximum (-1)

### ISSUE THREAD

**Issue by TristanHorlamus** [FreeOpcUa/python-opcua#1029]
## Error message:
    Connect to opc.tcp://1.2.3.4:4840/OpcUa
    Received an error: MessageAbort(error:StatusCode(BadCommunicationError), reason:Chunk size (132) exceeded maximum (-1))
    Received an error: MessageAbort(error:StatusCode(BadCommunicationError), reason:Chunk size (132) exceeded maximum (-1))

## Code:
    from opcua import Client
    from opcua import ua
    srv_url = "opc.tcp://1.2.3.4:4840/OpcUa"
    srv_usr = "test"
    srv_pwd = "test123"
    print("Connect to %s" % (srv_url))
    srv = Client(srv_url)
    srv.set_user(srv_usr)
    srv.set_password(srv_pwd)
    srv.connect()

**Comment by oroulet** [comment]
Ok. Someone changed that value. But your server is probably broken. What server is it?

**Comment by TristanHorlamus** [comment]
wouldn't be able to tell. For the moment I locked down my application to install opcua==0.98.9 till the issue gets resolved.
What's the value I am looking for? Maybe I could just change this after creating the client?

**Comment by oroulet** [comment]
def __init__(self):
        self.ProtocolVersion = 0
        self.ReceiveBufferSize = 2**32 - 1
        self.SendBufferSize = 2**32 - 1
        self.MaxMessageSize = 0  # No limits
        self.MaxChunkCount = 0  # No limits

try to change things somewhere in uaprotocol_hand.py and let me know what works

**Comment by TristanHorlamus** [comment]
I reverted commit 97caf7f28afa0850441c3cc320838c7bb5b730f4
that seems to solve the problem

**Comment by oroulet** [comment]
Can you try to find out what is the max value your server accepts? That might help many users

**Comment by oroulet** [comment]
Also what server do you have that crashes on that?

**Comment by TristanHorlamus** [comment]
2**31 - 1 is the maximum my server accepts.
Server is "SPPA-T3000-OPC_UA_Server" Vendor is "Siemens"

**Comment by oroulet** [comment]
Thanks. Let's make that the default

**Comment by oroulet** [comment]
Can you send a or?

**Comment by TristanHorlamus** [comment]
not sure what 'send or' means
