### ISSUE TITLE
.../opcua/common/node.py => Node class => __str__ and __repr__ method

### ISSUE THREAD

**Issue by AndreasHeine** [FreeOpcUa/python-opcua#1057]
Hey guys i plan to make a PR on Nodeclass as seen from the topic its about the "__str__" and the "__repr__" methods

https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/common/node.py
```
    def __str__(self):
        return "Node({0})".format(self.nodeid)
    __repr__ = __str__
```

what i like to change is that if you cast a node to string 
Now: "str(node)" & "repr(node)" => Node(NumericNodeId(ns=2;i=2))
After: "str(node)" => "ns=2;i=2" and if you call repr(node) => Node(NumericNodeId(ns=2;i=2))

what is your opinion?

@oroulet

**Comment by oroulet** [comment]
Sounds correct. Having str and repr the same is a bit of an abuse

**Comment by AndreasHeine** [comment]
@oroulet => #1058 tell me if its not ok

**Comment by AndreasHeine** [comment]
`__repr__ = __str__`

is used in many places in the same way i could change them in the same manner if you like!?

**Comment by swamper123** [comment]
> 
> 
> `__repr__ = __str__`
> 
> is used in many places in the same way i could change them in the same manner if you like!?

This seems to be usefull, especially when you rewrite both.

**Comment by oroulet** [comment]
This makes sense for nodeid since they have a specified string representation. But do other objects have such a representation?

**Comment by AndreasHeine** [comment]
maybe Browsname would make sence

of cource only in these cases where it makes sence

**Comment by oroulet** [comment]
Ok.
