### ISSUE TITLE
No name 'ua' in module 'opcua'

### ISSUE THREAD

**Issue by xuplus6493** [FreeOpcUa/python-opcua#1066]
Hello,
I have install opcua
but when I use this code by Visual Code  (Python 3.8.2 32bit)
`
from opcua import Client,ua
`
I get the problem

No name 'ua' in module 'opcua' (no-name-in-module)
![image](https://user-images.githubusercontent.com/55418235/83911372-b87b9680-a79e-11ea-9089-733b35077f24.png)

How can I fix it ?

**Comment by AndreasHeine** [comment]
have you checked the folders? C:\Users\<your login>\AppData\Local\Programs\Python\Python37\Lib\site-packages\opcua
![folder](https://user-images.githubusercontent.com/56362817/83910700-4c336f80-a76b-11ea-8e07-8cc128e7c5e5.PNG)

**Comment by oroulet** [comment]
Your installation is completely broken. Try again

**Comment by xuplus6493** [comment]
> have you checked the folders? C:\Users<your login>\AppData\Local\Programs\Python\Python38\Lib\site-packages\opcua
> ![folder](https://user-images.githubusercontent.com/56362817/83910700-4c336f80-a76b-11ea-8e07-8cc128e7c5e5.PNG)

yes，I have this file

**Comment by AndreasHeine** [comment]
try:
python -m pip uninstall opcua
and finaly
python -m pip install opcua

**Comment by xuplus6493** [comment]
> Your installation is completely broken. Try again

I have try 
pip uninstall opcua
pip install opcua

**Comment by AndreasHeine** [comment]
(-_-) do you have python 2 also installed ?

**Comment by xuplus6493** [comment]
> (-_-) do you have python 2 also installed ?

no, only python 3

**Comment by AndreasHeine** [comment]
have you tried comandprompt with admin priviliges and then => python -m pip uninstall opcua =>  python -m pip install opcua

**Comment by xuplus6493** [comment]
> have you tried comandprompt with admin priviliges and then => python -m pip uninstall opcua => python -m pip install opcua

I did, but it's not working

![image](https://user-images.githubusercontent.com/55418235/83911779-70a93f00-a79f-11ea-9d89-99cc97554423.png)

**Comment by xuplus6493** [comment]
> Your installation is completely broken. Try again

I have reinstall python, visual code and opcua ...

**Comment by AndreasHeine** [comment]
and? win/fail?

**Comment by xuplus6493** [comment]
fail ...

**Comment by AndreasHeine** [comment]
open python shell:
print( help('modules'))

**Comment by xuplus6493** [comment]
> open python shell:
> print( help('modules'))

![image](https://user-images.githubusercontent.com/55418235/83913534-29707d80-a7a2-11ea-929b-9de0281fcb69.png)
![image](https://user-images.githubusercontent.com/55418235/83913545-2d9c9b00-a7a2-11ea-9d51-86a7add9034e.png)

**Comment by AndreasHeine** [comment]
if u use pythons builtin IDE -> "idle" does it also blame that there is no "ua"

**Comment by xuplus6493** [comment]
> if u use pythons builtin IDE -> "idle" does it also blame that there is no "ua"
![image](https://user-images.githubusercontent.com/55418235/83914401-bd8f1480-a7a3-11ea-8d93-225c81f2dd49.png)

**Comment by xuplus6493** [comment]
I want to writ Tag  (kepware server)
the same code is work on another computer
![image](https://user-images.githubusercontent.com/55418235/83914543-ff1fbf80-a7a3-11ea-9d1e-fb9793d5a5ce.png)

**Comment by AndreasHeine** [comment]
yeah because ua.VariantType.Double is missing... then you'll get BadTypeMismatch !!!

**Comment by xuplus6493** [comment]
> yeah because ua.VariantType.Double is missing... then you'll get BadTypeMismatch !!!

How to get  ua.VariantType.Double ?

my tag data type is "Double"

**Comment by AndreasHeine** [comment]
you will not like my answer...

`from opcua import ua`

**Comment by xuplus6493** [comment]
> you will not like my answer...
> 
> `from opcua import ua`

![image](https://user-images.githubusercontent.com/55418235/83915476-def10000-a7a5-11ea-9bda-abdf048de00b.png)

**Comment by xuplus6493** [comment]
> opcua datatypes and python datatypes are different so you have to be specific what opcuatype you want to set!
> 
> "var = 1" is an Python int => OPCUA Int 64


But, the same code is working in another computer....

**Comment by AndreasHeine** [comment]
well then its more likely your pc is the problem...

**Comment by xuplus6493** [comment]
> well then its more likely your pc is the problem... sorry

Thank you for your help !

**Comment by xuplus6493** [comment]
I solve this problem !!
pip install  copyright

**Comment by gauravbvelex** [comment]
@xuplus6493  Could you please provide steps about how did you fix it? "pip install copyright" is vague.
