### ISSUE TITLE
missing f-string or .format() at some places

### ISSUE THREAD

**Issue by AndreasHeine** [FreeOpcUa/python-opcua#1071]
while working on asyncua PR211 i saw some of these and in python-opcua aswell:

```python
def _to_val(objs, attr, val):
    from opcua import ua
    cls = getattr(ua, objs[0])
    for o in objs[1:]:
        cls = getattr(ua, _get_uatype_name(cls, o))
    if cls == ua.NodeId:
        return "NodeId.from_string('val')"  # <------------------------!
    return ua_type_to_python(val, _get_uatype_name(cls, attr))
```

if it does not return a f-string it is unable to pass val into the string!?

@oroulet : ???

**Comment by swamper123** [comment]
Where is that snippet located?

**Comment by AndreasHeine** [comment]
schemas / generate address space

**Comment by swamper123** [comment]
This is correct.
I will have a look in general over other lines, where f-string could be added (for performance) and possible typos like this one.

**Comment by oroulet** [comment]
yes something worng in code over. IT is strange there it is not caught by any tests. Is it such a special case?

**Comment by swamper123** [comment]
possible .format replacements with f-strings:
- generate_ids.py
- download.py
- generate_address_spaces.py
- generate_events_objects.py
- generate_model.py
- generate_protocol_python.py
- generate_statuscode.py
- uaprotocol_auto_add.py

possible typos?
- generate_address_space.py, line 150
- generate_event_objects.py, line 47

others haven't been found at the moment.

**Comment by oroulet** [comment]
.format still work in python  3. but it is nice to fix anyway
Concerning the typos can you send link to code on github? the line number is not easy to use with all these different branches...

**Comment by swamper123** [comment]
The first:
https://github.com/FreeOpcUa/python-opcua/blob/f761ccf0882daff8f000885e851db66b3c0ea167/schemas/generate_address_space.py#L150

and the second one:
https://github.com/FreeOpcUa/python-opcua/blob/f761ccf0882daff8f000885e851db66b3c0ea167/schemas/generate_event_objects.py#L47

On the first sight they seem to be a similar problem, but I could be wrong.
The format stuff was just for possible performance stuff, if we are touching some strings in that case anyway.

**Comment by oroulet** [comment]
I am not sure at all these are typos. This is code written for code generation and somethings it looks quite strange. Maybe you have a varaible called "message" in the generated code.
The first one looks correct because there is for sure a variable called ua.ObjectIds.String in the generated code.

**Comment by oroulet** [comment]
but that line `return "NodeId.from_string('val')"`is suspicious because even if there is a variable called val in code, then it is written as a string...

**Comment by AndreasHeine** [comment]
```python
    if cls == ua.NodeId:
        return f"NodeId.from_string('{val}')"
```

this is never called at all...
