### ISSUE TITLE
Setting the Status Code

### ISSUE THREAD

**Issue by Dhruva0707** [FreeOpcUa/python-opcua#1079]
I want to create an opcua server, which reads values from sensors and sets the values of its own nodes accordingly. However, sometimes, the sensor does not return any value. At this point, I want to set the status code of that node to for any subscription "BadDataUnavailable". Is it even possible to do so?

**Comment by oroulet** [comment]
find an example using DataValue and set the statuscode for the DataValue before writing it

**Comment by Dhruva0707** [comment]
Okay I will check that up!

**Comment by Dhruva0707** [comment]
Thanks a lot! that worked. :)
