### ISSUE TITLE
Get id of a node as the value of i and ns

### ISSUE THREAD

**Issue by ohidurbappy** [FreeOpcUa/python-opcua#1090]
In my subscription handler I want to get the id  of node. More specifically check what's the value of i and ns of a node id...

class SubHandler():
    def datachange_notification(self, node, val, data):
        print(datetime.now(), "- Data Change - ", val)
        i=node........
        ns=.......

    def event_notification(self, event):
        pass

**Comment by AndreasHeine** [comment]
> class SubHandler():
> def datachange_notification(self, node, val, data):
> print(datetime.now(), "- Data Change - ", val)
> i=node........
> ns=.......

since last release (0.98.12):
`str(node)` => returns a string like this "ns=4;i=1000"
then you could split in ";" then "=" or use a regex to get ns.

**Comment by ohidurbappy** [comment]
Thank you. It solves the problem.

**Comment by brubbel** [comment]
```
i = node.nodeid.Identifier
ns = node.nodeid.NamespaceIndex
```

**Comment by ohidurbappy** [comment]
> ```
> i = node.nodeid.Identifier
> ns = node.nodeid.NamespaceIndex
> ```

This is more neat solution.

**Comment by brubbel** [comment]
It is useful to keep in mind that Node is just some object wrapper around the NodeId + a server session, providing some useful tools to interact (e.g. get_value, get_browsename, ...) with the client proxy or the server.

pseudocode:
```
class Node:

    def __init__():
        self.nodeid
        self.session

   def useful_tools():
       ...
```

**Comment by AndreasHeine** [comment]
> i = node.nodeid.Identifier
> ns = node.nodeid.NamespaceIndex

good to know! havn't seen that, in the past i only used "ns=4;i=1000".
