### ISSUE TITLE
kepserver data event 

### ISSUE THREAD

**Issue by kashp** [FreeOpcUa/python-opcua#11]
Hi  oroulet 
I am connecting kepserver with python using python-opcua
I am polling the server for tag value change, Is there any event registration mechanism so that my python function triggered automatically as the tag value will change

Thanks

**Comment by oroulet** [comment]
Look at subscription in example client. Let me know if it works with kepware

**Comment by kashp** [comment]
Thanks oroulet its working thanks,
I have one more doubt, lets suppose i have registered 180 tags 
like this
sub.subscribe_data_change(myvar)

data_change(self, handle, node, val, attr) will be executed upon event receive. 
If all tags changed then this function will be called in parallel or sequential 
????

**Comment by oroulet** [comment]
In current implementation there is only one thread calling callbacks so all
calls will be sequential s. One could implement a thread pool but in
python, which is anyway monoprocess, I am not sure it would help anything

**Comment by oroulet** [comment]
One planned improvement is to allow subscriptions to many tags at once...
But not done yet
