### ISSUE TITLE
Please Set up the Discussions for Python-opcua.

### ISSUE THREAD

**Issue by Rajulearner** [FreeOpcUa/python-opcua#1186]
# Please Try to add Discussions tab. It is helpful for our community to discuss Questions, Without raising issues.
Many folks(including me) are facing issues while understanding the code or while implementing the opc-ua in their projects.
It is beneficial to everyone if we set up a discussions for this Project Repo.

**Comment by AndreasHeine** [comment]
you can also use gitter!

https://gitter.im/FreeOpcUa/python-opcua

https://gitter.im/FreeOpcUa/opcua-asyncio

**Comment by swamper123** [comment]
We should add that in README...

**Comment by oroulet** [comment]
done. so let's try it

**Comment by swamper123** [comment]
Perhaps for opcua-asyncio as well?!

**Comment by Rajulearner** [comment]
Thanks for your response @oroulet and every contributor of this wonderful project.
