### ISSUE TITLE
Module opcua.users doesn't exist

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#12]
I went from 0.9.3 to the latest, 0.9.6 (your commit from today). and when my client code hits the opcua import i get an error that the module opcua.user doesn't exist.

I'm very new to python so it could be that I've done something wrong, but when I go back and install 0.9.3 my code runs again.

Edit: Your July 5th commit is also working.

**Comment by oroulet** [comment]
Fixed now. Thanks
