### ISSUE TITLE
The client application name is not configurable.

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [FreeOpcUa/python-opcua#1215]
This is a bug report. to get help go to https://github.com/FreeOpcUa/python-opcua/discussions

**Describe the bug**
The client application name seems to be hardcoded as at
https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/client/client.py#L122 .

Can this be made configurable , so that I can provide custom name.
**To Reproduce**
Steps to reproduce the behavior incl code:

**Expected behavior**

**Screenshots**
Since the name is  very generic , server maintainer is not ready to whitelist our application,
![image](https://user-images.githubusercontent.com/9215832/103976326-784d1e00-519c-11eb-912b-b0b5e51cf594.png)

**Comment by AndreasHeine** [comment]
thats not an issue just a missunderstanding of the api
check the answer in discussions!
