### ISSUE TITLE
Accessing Historical Alarms and Events Over OPC A&E Server using Python / .NET / Java or any other platform

### ISSUE THREAD

**Issue by rajnishnationfirst** [FreeOpcUa/python-opcua#1229]
Hi ,

I am implementing and want to capture Historical Alarms and Events over OPC A&E Server  ( Not OPC UA or OPC HDA ) created in Siemens WinCC SCADA.

I tried HDA data over OPC UA and implemented in Python Free OPCUA SDK  and working fine. But the WinCC does not support the capturing Historical Alarms over OPC UA and yet the OPC UA has **node.read_events_history(start_time,end_time ,0)** , but i cannot use this function on OPCA&E server available in python .

The below is the snap of WinCC Siemens SCADA OPC A&E Server  and don't have node Ids and Tags configuration.

<img width="792" alt="alarms" src="https://user-images.githubusercontent.com/64892368/105332939-2aec9a00-5bfb-11eb-89ea-1f75ebefff5e.PNG">

Could any one help with some open source SDK's available in Python , .NET or Java or Java Script for OPC A&E Server capturing historical alarms and events. ?

Thanks and Regards

Rajnish Vishwakarma

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/python-opcua/discussions
