### ISSUE TITLE
Create folder/variable with node id like ns=2;s="foo.bar"

### ISSUE THREAD

**Issue by kevincolyar** [FreeOpcUa/python-opcua#126]
Is this possible?  It appears add_variable/add_folder only takes a namespace and name which generates node id's like ns=2;i=1234

**Comment by oroulet** [comment]
do you know any other SDK that accept quotation inside quotation?  ns=2;s=foo.bar should work.

**Comment by kevincolyar** [comment]
Sorry, the quotes aren't needed.

I tried passing ns=2;s=foo.bar to add_variable but it just made that it's name.  The node id was stil ns=2;i=1234

Do I need to pass it a node instance?

**Comment by oroulet** [comment]
Mynode.add_variable(nodeid, browsename) where args are either strings or
NodeId and QualifiedName

**Comment by kevincolyar** [comment]
Thanks @oroulet!

For reference, I was able to do:

```python
node.add_variable("ns=2;s=foo.bar", "bar", value)
