### ISSUE TITLE
remove debug print...

### ISSUE THREAD

**Issue by ulda** [FreeOpcUa/python-opcua#1285]
Somebody left a debug print in the code.
`diff --git a/remi/gui.py b/remi/gui.py
index c33b5fd..4c4dba3 100644
--- a/remi/gui.py
+++ b/remi/gui.py
@@ -2037,7 +2037,7 @@ class TabBox(Container):
     @decorate_set_on_listener("(self, emitter, key)")
     @decorate_event
     def on_tab_selection(self, emitter, key):
-        print(str(key))
+        #print(str(key))
         for k in self.children.keys():
             w = self.children[k]
             if w is self.container_tab_titles:
`

**Comment by AndreasHeine** [comment]
please copy and post the permalink!

**Comment by ulda** [comment]
I was not able to format the patch correctly within  the mail. I'l attache it here.
[remi-remove-print.patch.gz](https://github.com/FreeOpcUa/python-opcua/files/6136336/remi-remove-print.patch.gz)

**Comment by AndreasHeine** [comment]
Make a Pullrequest or tell us the file and line!

**Comment by ulda** [comment]
Oh, I thought the patch woud be sufficient.
But look at remi/gui.py line 2040

**Comment by AndreasHeine** [comment]
are you sure you are in the right repository?

**Comment by ulda** [comment]
O Sh...  <peinlich>  - Sorry.
