### ISSUE TITLE
Able to read values only if ua server is connected through ua expert. As soon as I close ua expert values are holding and same values are repeated .

### ISSUE THREAD

**Issue by GauravMundhra** [FreeOpcUa/python-opcua#1305]
Hi,
I have converted OPC-DA to OPC-UA , and now while reading through python opcua, if server is connected through ua expert and tags are listed, values from python opcua are coming right.
If I close ua expert values from python opcua does not update and holds to previous value.

Why server is dependent on ua expert client?

**Comment by AndreasHeine** [comment]
please stick to the bug report template!
and most important explain your setup more...
