### ISSUE TITLE
How to get the sProsys erver time in Client program

### ISSUE THREAD

**Issue by georgethomas08** [FreeOpcUa/python-opcua#1316]
I couldn't find any function to get the server time of prosys server is there any other way to retrieve it !

### Please read, before you post!

This is a _**BUG REPORT for issues in the existing code**_. 

If you have general questions, code handling problems or ideas, please use the:

Discussionsboard: https://github.com/FreeOpcUa/python-opcua/discussions <br/> or <br />
Gitter-Channel: https://gitter.im/FreeOpcUa/python-opcua

---

To save some time, please provide us following informations, if possible:

**Describe the bug** <br />

**To Reproduce**<br />
Steps to reproduce the behavior incl code. <br />
If you post code, please use the "insert Code" (which is the "< >" symbol) format for a better readability.

**Expected behavior**<br />

**Screenshots**<br />
If applicable, add screenshots to help explain your problem. <br />
You can post Screenshots directly to github, please don't use 3rd Party webpages

**Version**<br />
Python-Version:<br />
python-opcua Version (e.g. master branch, 0.9):

**Comment by swamper123** [comment]
This is not a Bug, so pls. use [Discussions](https://github.com/FreeOpcUa/python-opcua/discussions) to ask a question.
