### ISSUE TITLE
REST API to OPC UA Server

### ISSUE THREAD

**Issue by shnabin** [FreeOpcUa/python-opcua#1327]
Hi, 

I'm new to OPC UA and i have a requirement to read data from a REST API (data in json) & make the data available in OPC UA server, so OPC clients can connect to the server & gets the data. Its more like 

REST API --> OPC UA Server --> OPC Clients. 

I explored some options to check the possibility & its possible with [https://www.opc-router.com/4-rest-protocol-web-services_en/](url) , I am looking for a similar solution in FreeOpcUa (with out UI etc but as a solution), Can you please suggest how to achieve this

**Comment by swamper123** [comment]
This is not an issue, please use [Discussion](https://github.com/FreeOpcUa/python-opcua/discussions) for questions.
