### ISSUE TITLE
demo server code is broken

### ISSUE THREAD

**Issue by HaythemLtifi** [FreeOpcUa/python-opcua#1345]
Hello , not sure what is the problem but i think my library is broken .the minimal python sever code does no work. it compiles but do nothing.
I think the node.add_object is the broken one. can someone confirm?
using windows 10 and python 3.7.9
![image](https://user-images.githubusercontent.com/76454247/123935438-21c2de80-d98c-11eb-9786-17247dfe5fbc.png)

**Comment by AndreasHeine** [comment]
can you explain the issue?

**Comment by swamper123** [comment]
Please use the "Bug Report" Template next time.
Beside your choice of var names (which confuse me a bit), what exactly doesn't work? Is an issue thrown?

**Comment by HaythemLtifi** [comment]
node.add_object should return a object right? in my case it does not . param type is any. 
if you notice the add_variable color is not yellow. 
its as if node.add_object does not work

**Comment by HaythemLtifi** [comment]
> 
> 
> Please use the "Bug Report" Template next time.
> Beside your choice of var names (which confuse me a bit), what exactly doesn't work? Is an issue thrown?

yes i will thanks.
i think the node.add_object method has an issue . it does not return an object type

**Comment by HaythemLtifi** [comment]
same thing with the demo code
![image](https://user-images.githubusercontent.com/76454247/123951291-8be37f80-d99c-11eb-98f8-455ed95cd419.png)

**Comment by HaythemLtifi** [comment]
using this tool i found out that the server works , but the discolored throw me away..... sorry guys i am new and have been following a youtube video. 
but why the add_variable is not colored? in the video its colored . its like param is not an object. but it should be right?
![image](https://user-images.githubusercontent.com/76454247/123952702-432cc600-d99e-11eb-997a-56dfc30326d5.png)

**Comment by AndreasHeine** [comment]
> node.add_object should return a object right? in my case it does not . param type is any. 
> if you notice the add_variable color is not yellow. 
> its as if node.add_object does not work

it should return a nodeclass instance!

**Comment by AndreasHeine** [comment]
> same thing with the demo code
> ![image](https://user-images.githubusercontent.com/76454247/123951291-8be37f80-d99c-11eb-98f8-455ed95cd419.png)
> 

add_variable() is a method of the nodeclass instance

**Comment by AndreasHeine** [comment]
https://github.com/AndreasHeine/python-opcua/blob/bf9dc941acf4da53ebe7505108d885d9e77cee75/opcua/common/node.py#L31

**Comment by HaythemLtifi** [comment]
param type is any . IS it correct? shouldn't it be node?

![image](https://user-images.githubusercontent.com/76454247/123960136-db2ead80-d9a6-11eb-9709-94098fae8a4e.png)

**Comment by AndreasHeine** [comment]
does the server run with that variable or do you just complain about the wrong linting in vscode?

**Comment by HaythemLtifi** [comment]
it does run but i get this error  'Tried to read attribute  #'16' in TwoByteNodeId(i=33), but the attribute is missing'
so i assumed its all connected to the fact that the param type is not node its just any. not sure what is happening here.
thanks for your time man. very much appreciated
