### ISSUE TITLE
Application URI from server certificate

### ISSUE THREAD

**Issue by RakshanPremsagar** [FreeOpcUa/python-opcua#1361]
Hello,
I am testing an OPC UA server, and one of the basic tests  is that the ApplicationURI of the server certificate, should match the ApplicationURI of endpointDescriptions.

I could extract the endpoints of the server, I could extract the certificates as well. However, I do not seem to find a way to extract the ApplicationURI from the certificate.
Looking forward for some guidance here.

```
from opcua import *
if __name__ == "__main__":

    logging.basicConfig(level=logging.WARNING)
    endpointURL = "opc.tcp://localhost:48010"
    client = Client(endpointURL)
    client.connect()
    endpoints = client.get_endpoints()
    for endpoint in endpoints:
       serverCerti = endpoint.ServerCertificate  # how to extract  application URI from serverCerti here?

    applicationURI = endpoint.Server.ApplicationUri
```

And also, one conceptual question is, the test has to be performed without establishing the connection to the server. But I could not come up with the way to do so before connecting to the server.

**Comment by swamper123** [comment]
This is not an issue and you asked that already in discussions. - Close
