### ISSUE TITLE
OPC UA SERVEUR only works with  Basic256Sha256_SignAndEncrypt ?

### ISSUE THREAD

**Issue by HaythemLtifi** [FreeOpcUa/python-opcua#1363]
### Discussed in https://github.com/FreeOpcUa/python-opcua/discussions/1362

<div type='discussions-op-text'>

<sup>Originally posted by **HaythemLtifi** July 15, 2021</sup>
Hello,
i wanted to try the Basic256_Sign  SecurityPolicyType byt the UaExpert throw this error
i cant only connect if i set it to Basic256Sha256_SignAndEncrypt  .  i have labview client and i need the Basic256_Sign   to connect with it.
any help plz.
thanks 
![image](https://user-images.githubusercontent.com/76454247/125845483-9e945298-54e3-4de6-8f2a-6a4a08cc3cbc.png)
![image](https://user-images.githubusercontent.com/76454247/125845653-ddc84fbb-b5a9-49c6-8691-0b550dd9ae26.png)

![image](https://user-images.githubusercontent.com/76454247/125845334-074bf935-42d4-49e1-b06b-c78d74186662.png)
</div>

**Comment by AndreasHeine** [comment]
duplicate!

**Comment by HaythemLtifi** [comment]
sorry for the duplicate  i thought this is adequate to be and issue more than ask for help section  .
