### ISSUE TITLE
Building GUI

### ISSUE THREAD

**Issue by mertz3hack** [FreeOpcUa/python-opcua#139]
What is your opinion on the easiest way to build a GUI to interact with python opcua?

Has anyone used IronPython through Visual Studio?

**Comment by oroulet** [comment]
https://github.com/FreeOpcUa/opcua-client-gui

Build with qt, which is currently the best GUI library in my opinion.

Isn't iron Python dead? I thought Microsoft killed it

**Comment by mertz3hack** [comment]
IronPython isn't dead but isn't developed by microsoft anymore, only by a community which may no longer be working on it.
IQT seems to be what I am looking for!
I will comment back on my beginner experience with it later on

**Comment by oroulet** [comment]
It is far from finished so help is welcome
