### ISSUE TITLE
client.disconnect error

### ISSUE THREAD

**Issue by mertz3hack** [FreeOpcUa/python-opcua#141]
I have been getting the following error when disconnecting that I have not been able to figure out.
[clientdisconnecterror.txt](https://github.com/FreeOpcUa/python-opcua/files/153577/clientdisconnecterror.txt)

I am connecting with the following file.
[client.py.txt](https://github.com/FreeOpcUa/python-opcua/files/153581/client.py.txt)

This file is with Logging set to Debug.
[clientdebug.txt](https://github.com/FreeOpcUa/python-opcua/files/153579/clientdebug.txt)

Any thoughts on getting rid of this error?

**Comment by oroulet** [comment]
Seems to be a Windows specific error when cancelling a read operation. I
can add a try/catch there but this looks like an error without consequence

**Comment by mertz3hack** [comment]
@oroulet I have gotten the same error with new python installations of 3.4.0, 3.4.4, and 3.5.1

**Comment by oroulet** [comment]
Yes you do,  but I still think this is not really an important issue

**Comment by mertz3hack** [comment]
@oroulet 
So this issue wasn't affecting me when I was running a python script but I tried to go one step farther using py2exe
The exe would always show a disconnect error pop up after the exe is disconnected and closed
My current solution to avoid the error (which is not a good solution) is to just not disconnect since the server will eventually kick the user for inactivity

**Comment by oroulet** [comment]
ok let's try to catch it...

**Comment by mertz3hack** [comment]
@Any suggestion on where/how to track this?

**Comment by oroulet** [comment]
Well the stack trace tells everything:
le "..\opcua\common\utils.py", line 101

Add oserror to the try catch and send a pull request

**Comment by mertz3hack** [comment]
@oroulet sorry nOOb here.  I need a little more information on what you want me to do

**Comment by oroulet** [comment]
I implemented it already. The last version on pip should have the fix. Do you still get the error?

**Comment by mertz3hack** [comment]
@oroulet seems to be working! Thanks now I will just have to track back the change log to see what you did.  Do you know which commit it was solved in?  I have been MIA for a bit and haven't watched a bunch.

I also didn't know this project was on pip!

**Comment by mertz3hack** [comment]
https://github.com/FreeOpcUa/python-opcua/commit/b88ad958ea3b240dfa5a51aa13c8347ea572c783
