### ISSUE TITLE
Regarding Windows Server is getting hanged from last 1 week when accessing a WinCC SCADA Server.

### ISSUE THREAD

**Issue by rajnishnationfirst** [FreeOpcUa/python-opcua#1425]
Hi  colleagues,

There are 2 servers 149  ( WinCC SCADA Server ) and 151 (  Web Server ).

The 151 server i having a OPCUA Client written in Python Free OPCUA . 

This client was running fine from last 2 years , but from last week the Web Server ( 151 ) is getting hanged when i run the same program and i am not able launch it via RDP ( Remote Desktop Protocol ) and the Remote Desktop Protocol  only shows the below message and stucked at this stage and continuously shows the message.

![image](https://user-images.githubusercontent.com/64892368/145869101-0e40f5f7-275e-43a8-94ef-2e12403a52eb.png)

Also from last a different vendor is also trying to connect the same WINCC System , from then this problem has started .

Is there network issue ? or Deadlock Issue ? or any issue pertaining the same access .

Pls help me resolve this issue .

Pls suggest me what  to do to overcome such weird problem.

Thanks

Rajnish Vishwakarma

**Comment by AndreasHeine** [comment]
this is more likely an issue in your system not with OPC UA...
ask yourself what has changed in the last weeks!

**Comment by swamper123** [comment]
If you got can't get access via RDP, than you got other problems. If you got access to the server, you might have to reboot it or get access on it localy to figure stuff out.
As long as there isn't any code snippet, logs or sth. else, we can't say "that might be repo-relevant".
