### ISSUE TITLE
Server side refresh rate

### ISSUE THREAD

**Issue by om327** [FreeOpcUa/python-opcua#1440]
Hello, 

I've created a very simple Python OPC UA server using the asyncio library. This is subscribed to from a simple NodeJS OPC UA client. I've notice there is a lag of around 5 seconds for the server to update. At first i assumed this was due to NodeJS but I've checked with the UAExpert Client and this is also seeing a 5 second lag between updates - even though on he python server side the code polling the equipment is reciving new values ever 500ms.

Is there a setting to increase the refresh rate ffor the python server or is this hard coded?

Many thanks!
Ollie

**Comment by AndreasHeine** [comment]
you are probably in the wrong repo!
--> https://github.com/FreeOpcUa/opcua-asyncio
