### ISSUE TITLE
User authentication has security bug

### ISSUE THREAD

**Issue by ryangu18** [FreeOpcUa/python-opcua#1457]
**Describe the bug** <br />
User authentication has security bug, even enable server.set_security_IDs(“Username”)，But I can log still in anonymously

**To Reproduce**<br />
Steps to reproduce the behavior incl code. <br />
The code comes from here https://github.com/FreeOpcUa/python-opcua/issues/1153#issuecomment-713593224
it is Mr. AndreasHeine's demonstration code, I didn't make any changes.  <br />

**Expected behavior**<br />
Create a ua server, the security policy is Basic256Sha256_SignAndEncrypt , the authentication user/pwd is 'user1' and 'pw1' <br />

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/99937589/165244517-4254446f-c846-483b-9f4b-4b5ddb1c50b5.png)

This screenshot is as expected, we see the security policy, and can only authenticate with username and password, anonymous is disabled,  Select ok, then, we do not connect to this server, but right-click to open properties,
![image](https://user-images.githubusercontent.com/99937589/165245793-1c1d93f3-88b8-4403-b887-27412230b601.png)
At this time I see that Anonymous has been enabled, choose anonymous,
![image](https://user-images.githubusercontent.com/99937589/165247533-e79f7fa1-6fbc-4650-8976-ea94d587f1bb.png)

 ok , and  connect to the server, we see that the server has been connected without entering a password.

![image](https://user-images.githubusercontent.com/99937589/165246531-2d2434f9-923c-4fb0-b320-99b93430c8e8.png)

**Version**<br />
Python-Version:  python 3.9 64bit<br />
python-opcua Version (e.g. master branch, 0.9): 0.98.13
![image](https://user-images.githubusercontent.com/99937589/165247036-09514adb-88a3-4455-b84b-20416be012b3.png)

**Comment by schroeder-** [comment]
UAExpert allows to select every Security Policy even if it is not support, if you go over the Properties.

**Comment by AndreasHeine** [comment]
nether the less it should not be able to connect with anonymus...

**Comment by ryangu18** [comment]
Note that the security policy and authorization for this server are set in the code

server.set_security_policy([
                                    # ua.SecurityPolicyType.NoSecurity,
                                    # ua.SecurityPolicyType.Basic128Rsa15_Sign,
                                    # ua.SecurityPolicyType.Basic128Rsa15_SignAndEncrypt,
                                    # ua.SecurityPolicyType.Basic256Sha256_Sign,
                                    ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt
                                ])
    policyIDs = ["Username"]

My problem was that I bypassed the password entry using the method above.
If it's not a bug, sorry for my bad submission, but how do I make my expectations valid? "Anonymous login is prohibited and must be authorized with username, password

**Comment by schroeder-** [comment]
I quickly scanned through the code and I think the server always accepts ever UserToken even if it is disabled via set_security_policy. The server only provides the supported UserTokens for discovery/GetEndpoints, but on create_session this is not check.

**Comment by AndreasHeine** [comment]
should be checked in activate session!
![image](https://user-images.githubusercontent.com/56362817/165253721-981243fa-f385-4925-bb0a-27aaaf56d98b.png)

**Comment by schroeder-** [comment]
Its not see:
[It     
    id_token = params.UserIdentityToken
        if isinstance(id_token, ua.UserNameIdentityToken):
            if self.user_manager.check_user_token(self, id_token) == False:
                raise utils.ServiceError(ua.StatusCodes.BadUserAccessDenied)
        self.logger.info("Activated internal session %s for user %s", self.name, self.user)](https://github.com/FreeOpcUa/python-opcua/blob/858274721766907148b527916e97446dbbf6af6d/opcua/server/internal_server.py#L348-L353)

I can provide a pr in the next days.

**Comment by AndreasHeine** [comment]
@schroeder- could you check asyncua aswell probably the same there!

**Comment by schroeder-** [comment]
@AndreasHeine same, I can provide the same fix there.
