### ISSUE TITLE
What is TIMESTAMP UNSPECIFIED?

### ISSUE THREAD

**Issue by vvpnet** [FreeOpcUa/python-opcua#1497]
Hello colleagues!

I'm having problems here:
https://github.com/FreeOpcUa/python-opcua/blob/2cfc9bc8f01d18e1b92d3410f7fb328df6950bfa/opcua/ua/uatypes.py#L47

The freeOpcUa client cannot correctly read the history from getHistoryData_service_default
because it has UNSPECIFIED defined as "-1" (1601-01-01 12:00AM UTC).
https://github.com/open62541/open62541/blob/ae74dc0071cc58cf96abeeaf7b9c6c39dd2ed286/plugins/historydata/ua_history_database_default.c#L45

And in open62541 UNSPECIFIED as LLONG_MIN "-9223372036854775808".
So is there a TIMESTAMP UNSPECIFIED?

**Comment by AndreasHeine** [comment]
The library is deprecated.
Please switch to : [opcua-asyncio](https://github.com/FreeOpcUa/opcua-asyncio) which also has a [sync-wrapper](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/sync.py), with very few changes in API**
