### ISSUE TITLE
Improve node method get_data_type

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#151]
The way it is right now ```node.get_data_type()``` only returns the xNodeID with ObjectID. You then have to look up the OPC UA spec or go into object_ids.py and decode it.

Is there a reason the high level method can't also return a string of the data type?

**Comment by oroulet** [comment]
Good point. We should auto generate reverse objectids. You can open bug
request and even better implement it look at py files under schema directory

**Comment by oroulet** [comment]
ObjectIs cannot be enum has this is has huge performance impact. The reversed objectId dict is now created but it would be strange to return a string instead of a nodeid. so I have no better idea on how to solve this...

**Comment by zerox1212** [comment]
I understand more or less now. I suppose the only option would be to add ```node.get_data_type_as_str()``` method, but I realize node already has many methods...

It isn't that important, when I was originally using it, it just happened to return something I didn't expect because I didn't fully understand the OPC UA spec.

**Comment by zerox1212** [comment]
For reference the object id dict is used, but you need to import the module explicitly. The XML exporter can be used as an example, it uses the reverse look up.

Closing.
