### ISSUE TITLE
Cannot get value from alias

### ISSUE THREAD

**Issue by Flock1993** [FreeOpcUa/python-opcua#1513]
I am trying to get value of OPC tag s7:[501CS100]501LV100Q01J01
Where 
501CS100 - node
511WF150A01F01 - alias
Namespace_index is 3 for s7.
To seach alias in tree i use this code:
```
import asyncua
from asyncua.common import ua_utils
from tqdm.notebook import tqdm

A_ID = 1
NAME_ID = 3


async def print_node(node, node_obj, i=0):
    """Node printing"""
    node_obj["id"] = ua_utils.val_to_string(await node.read_attribute(A_ID))
    node_obj["name"] = ua_utils.val_to_string(await node.read_attribute(NAME_ID))
    ch = await node.get_children()
    node_obj["children_count"] = len(ch)
    if i == 10:  # depth limitation
        return node_obj
    if len(ch) > 0:  # checking for leaves
        for c in tqdm(ch):
            node_obj["children"].append(await print_node(c, {"id": "", "children": []}, i + 1))
    return node_obj


async def main(node_id: str):
    client = asyncua.Client(url="my_url", timeout=5)

    await client.connect()
    root = client.get_node(node_id)
    root_node = {"id": "Root", "children": []}

    tree = await print_node(root, root_node)
    await client.disconnect()
    return tree


tree = await main("ns=3;s=501CS100")
```

But the result is a dictionary where there is no alias, here is part of it:
```
{"id": "ns=3;s=501CS100.db456",
"children": [{"id": "ns=3;s=501CS100.db456.length",
              "children": [],
              "name": "LocalizedText(Locale='en', Text='db456.length')",
              "children_count": 0},
             {"id": "ns=3;s=501CS100.db456.0,b",
              "children": [],
              "name": "LocalizedText(Locale='en', Text='db456.0,b')",
              "children_count": 0}],
"name": "LocalizedText(Locale='en', Text='db456')",
"children_count": 2}
```
If i use this code:
```
node = client.get_node(f"ns=3;s=501CS100.501LV100Q01J01")
value = await node.read_value()
print(value)
```
I have error BadNodeIdUnknown: "The node id refers to a node that does not exist in the server address space."(BadNodeIdUnknown)

How i can get alias and value of it?
When i use Siemens OPC Scout i can see alias 501LV100Q01J01
![image](https://user-images.githubusercontent.com/86944512/227128818-9d408fa5-9a74-45f1-8668-b82b12748662.png)

And if i use MatrikonOPC Explorer i can see it too. (Example for another tag, but it has the same problem)
![image](https://user-images.githubusercontent.com/86944512/227129164-8dfe681d-f835-4596-b6e0-aa0d993d36a1.png)

**Comment by AndreasHeine** [comment]
you should post the error ^^

**Comment by Flock1993** [comment]
@AndreasHeine 
From this code:
```
node = client.get_node(f"ns=3;s=501CS100.501LV100Q01J01")
value = await node.read_value()
print(value)
```
Error is: BadNodeIdUnknown: "The node id refers to a node that does not exist in the server address space."(BadNodeIdUnknown)

**Comment by AndreasHeine** [comment]
first of all BadNodeIdUnknown is a ErrorResponse from the OPC UA Server that the NodeId ("ns=3;s=501CS100.501LV100Q01J01) does not exist in the Servers-Addressspace!

how do you get the NodeId? can you show me a Screenshot from UaExpert which shows the Attributes and References of that Node you mention!?

**Comment by Flock1993** [comment]
- NodeID 501CS100 and alias 501LV100Q01J01 i find from Siemens OPC Scout
- alias 501LV100Q01J01 Is not a descendant of node 501CS100, but i need to get it value
- I cannot use UaExpert now, i have only two screenshots above

**Comment by AndreasHeine** [comment]
i need to know what the references of your aliasfolder are... if you use get_children() it might not work with the BrowseParams...

**Comment by AndreasHeine** [comment]
did you use the Server-Methods to get the NodeId (https://reference.opcfoundation.org/Core/Part17/v104/docs/5) or Browse and Read your own way thru?

edit: 
FindAlias-Method -> https://reference.opcfoundation.org/Core/Part17/v104/docs/1.9.2

**Comment by Flock1993** [comment]
Thanks for reference.opcfoundation.org information!
If i execute this:
```
node = client.get_node(f"ns=3;s=501CS100")
children = await node.get_children()
print(children)
```
I get this list:
```
[
Node(NodeId(Identifier='501CS100.statepath', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.statepath', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.consistence', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.vfdstate', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.identify', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blocks', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.configuration', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.password()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blockread()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blockwrite()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blocklinkin()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blockdelete()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.blockcompress()', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>)),
Node(NodeId(Identifier='501CS100.buffers', NamespaceIndex=3, NodeIdType=<NodeIdType.String: 3>))
]
```
I now that there is such an appropriate
501LV100Q01J01=DB3002,REAL14
And there is child of 501CS100.db3002., which has 2 descendants: "length" and "0,b"
When i execute get_node -> read_value from 501CS100.db3002.length and 501CS100.db3002.0,b
They have int constant values, but this is not what I need.

**Comment by AndreasHeine** [comment]
get_children(<your node>) returns a list and it does not contain what you are looking for, but you know that there should be such a node right?

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/python-opcua/blob/fdf5f3c6c8655c90b0d36ce6a8db54749e8daeb4/opcua/common/node.py#L294

get_children() makes a BrowseRequest to the Server with the default params: 
ua.ObjectIds.HierarchicalReferences
ua.NodeClass.Unspecified
and
ua.BrowseDirection.Forward

so it only returns nodes with a HierarchicalReferences (e.g. "HasComponent") which are Forward (so no "ComponenOf" referenced Nodes) and all types of nodes -> NodeClass.Unspecified (Objects, Variable, Views, Types, ...)

https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.2/

**Comment by Flock1993** [comment]
@AndreasHeine
Can i execute FindAlias method by opcua-asyncio method to find node from alias?
Are there any functions in the library that execute native OPC commands?

**Comment by schroeder-** [comment]
Yes 
```Python
obj = client.get_node(ua.ObjectIds.Aliases)
alias_filter = '501LV100Q01J01'
alias_ref = ua.ObjectIds.AliasFor
res = await obj.call_method("FindAlias", alias_filter, alias_ref)
```

**Comment by Flock1993** [comment]
@schroeder
There is an error after code execution:
`BadNodeIdUnknown: "The node id refers to a node that does not exist in the server address space."(BadNodeIdUnknown)`

**Comment by Flock1993** [comment]
I want to test alias by local OPC UA.
I have one variable and want to set alias to it.
Is it goog to set alias by this way?:
```
async with Client(url="opc.tcp://admin@localhost:4840/freeopcua/server/") as client:
    var = await client.nodes.root.get_child(
        ["0:Objects", f"2:MyObject", f"2:MyVariable"]
    )
    alias = ua.LocalizedText("MB0")
    await var.write_attribute(ua.AttributeIds.DisplayName, ua.DataValue(alias))
```

**Comment by Flock1993** [comment]
Closing the issue, it was not OPC UA, but OPC DA with fake UA shell.
