### ISSUE TITLE
client PublishRequest timeout

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/python-opcua#152]
check what timeout we send publishrequest with (9e8). Ideally we should use 0, try 0 again. Otherwise we need to use thread to resend publish requests that have timeouted on server.
This is critical if no event happen within timeout period

This issue is solved on server side.

**Comment by georgschoelly** [comment]
The spec Part 4, 7.28 states:

> The Server shall check the `timeoutHint` parameter of a `PublishRequest` before processing a `PublishResponse`. If the request timed out, a `Bad_Timeout` Service result is sent and another `PublishRequest` is used.

Doesn't that just mean that we can catch `BadTimeout` in the publish callback handler and re-send another publish request?

**Comment by oroulet** [comment]
@georgschoelly yes, might be a solution. Although using 0 seems even better... if servers support it

**Comment by georgschoelly** [comment]
I created a quick pull request, but I don't have a setup ready to test this. Do you have something where you could easily test it? If not, I'm going to give it a try later.

**Comment by destogl** [comment]
After #282 this should be solved?!

**Comment by georgschoelly** [comment]
@destogl: Not really. The code still uses `9e8` as the timeout. As oroulet says, `0` (= no timeout) would be better.  I don't know what the problem was with `0`, so I don't know if we can just replace `9e8` with `0`.

**Comment by oroulet** [comment]
I think some servers had issues with 0. But we can try again, so we follow correctly spec. Send pr

**Comment by ramirahikkala** [comment]
I'm working with Festo PLC and it has an OPC UA server that doesn't allow 9e8 as a timeout but works with 0.
