### ISSUE TITLE
Malformed packages: CreateSessionResponse and ActivateSessionResponse

### ISSUE THREAD

**Issue by destogl** [FreeOpcUa/python-opcua#154]
By debugging of some errors between python-opcua and freeopcua libs I found out that recently we introduced a new bug... CreateSessionResponse and ActivateSessionRequest are not recognised by Wireshark but marked as malformed (s. picture below)

Can someone confirm this?

![bildschirmfoto2](https://cloud.githubusercontent.com/assets/1918204/14351662/d04cf16e-fcd0-11e5-88f2-0eb0ab68cae7.png)

**Comment by oroulet** [comment]
Probably the change to send null string instead of string of length 0. I
had to revert it once already. Do you see where the parsing fails? In the
box under


>

**Comment by destogl** [comment]
`CreateSessionResponse` seams to break on/after `RevisedSessionTimeout`:

![bildschirmfoto2](https://cloud.githubusercontent.com/assets/1918204/14360747/13e93816-fcf8-11e5-9c2c-970f4e314c5d.png)

`ActivateSessionResponse` on/after `AdditionalHeader`:

![bildschirmfoto2](https://cloud.githubusercontent.com/assets/1918204/14360775/3b58c9f2-fcf8-11e5-8407-dd62c7f89823.png)

**Comment by oroulet** [comment]
I just checked on my pc and I do not have the issue. Using wireshark 2.0.1 and freeopcua master

**Comment by destogl** [comment]
OK, I was using 1.10.6 version from Ubuntu repositories.

Install the version 2.0.2 from [stable ppa](https://launchpad.net/~wireshark-dev/+archive/ubuntu/stable) the error doesn't exist any more :+1: 

Sorry for false alarm, but it is good we cleared it!
