### ISSUE TITLE
autogenerated events

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/python-opcua#197]
@destogl CustomeEvent class is flagged as auto-generated but I cannot find any script generating it. ??

**Comment by destogl** [comment]
I flagged it since it was idea that we auto-generete it. in #159 you mentioned you wrote already some code for it. Do you have something? If not than we should write it...

**Comment by oroulet** [comment]
OK. I was just wondering. Yes i started some code, I should check it in, even if it is not finished. I had to prioritize other things

**Comment by georgschoelly** [comment]
@oroulet: That would be a big part of what I need for implementing a nicer interface for the alarms. (It already works using just the event functionality, but it's not nice to use and somewhat difficult to figure out.)

**Comment by destogl** [comment]
Closed in #406
