### ISSUE TITLE
typo error in opcua/client/client.py

### ISSUE THREAD

**Issue by Thus0** [FreeOpcUa/python-opcua#199]
Hi,

I've tried to connect to an OPC-UA server with certificate ; and there is a typo error in client.py 

https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/client/client.py#L386

` self._add_cetificate_auth(params, certificate, challenge)`

instead of

`self._add_certificate_auth(params, certificate, challenge)`

Best regards,

Pierre Nguyen

**Comment by oroulet** [comment]
thanks, fixed
