### ISSUE TITLE
Create custom objects

### ISSUE THREAD

**Issue by bitkeeper** [FreeOpcUa/python-opcua#209]
The Node.add_object let you only create object of the type BaseObjectType. It would be nice if you also could create other types by providing an objecttype.

Like:
  myobj = objects.add_object(idx, "MyCustomObject", myobjectype_nodeid)

Example and patch are included.

[customobjecttype_example.zip](https://github.com/FreeOpcUa/python-opcua/files/315627/customobjecttype_example.zip)

[manage_nodes_customobjecttypes.py.zip](https://github.com/FreeOpcUa/python-opcua/files/315593/manage_nodes_customobjecttypes.py.zip)

**Comment by destogl** [comment]
Could you create Pull request?

**Comment by oroulet** [comment]
A few months ago I started a method called instantiate  in instantiate.py ( not finished ). is it what you are looking it? Does your code replace it? Or should we merge these things?

**Comment by bitkeeper** [comment]
@destogl : pull request is done

@oroulet : differs from instantiate.py. The only thing this patch do is adding an additional argument to the add_object for providing a NodeId for the TypeDefinition.
