### ISSUE TITLE
BadNodeIdInvalid

### ISSUE THREAD

**Issue by davidschranz** [FreeOpcUa/python-opcua#218]
Siemens supplies with its CNC an OPC UA Server called AccessMyMachine. I was able to readout values using freeopcua-0.10.11 without any problems on one machine. On another machine I get an error BadNodeIdInvalid on some values. Using a test client from UA called UAExpert I can readout all values from both machines.

node=client.get_node( "ns=2;s=/DriveVsa/DC/R0035[u5]")
value=node.get_value()
opcua.common.uaerrors.UaStatusCodeError: The syntax of the node id is not valid.(BadNodeIdInvalid)

Could anyone give me a hint how to get this resolved.

**Comment by zerox1212** [comment]
When you subscribe to the node in UAExpert what do the NodeId attributes look like?

For example here is a screenshot of a OPC UA test server. This should give you a clue on what to pass to the ```get_node(0)``` method.

**Comment by davidschranz** [comment]
Here the screenshot of the attributes:
![capture](https://cloud.githubusercontent.com/assets/20048529/16225132/7aeabd54-37a5-11e6-8460-0e0273ea9932.PNG)

**Comment by oroulet** [comment]
in your screenshot the identifier is /DriveVsa/DC/R0035 not
/DriveVsa/DC/R0035[u5].
The error seems to say that your server does not support the "["
character....

**Comment by davidschranz** [comment]
This server somehow only shows the first parameter of an array. The other values would have to be with brackets:
![python02](https://cloud.githubusercontent.com/assets/20048529/16228028/aa37b1fc-37b4-11e6-9eb4-70ffe10b0b4b.PNG)

I have two servers, whereas the python call works on one server but not on the other one. Using the UAExpert, I get a result back from both servers:
![python03](https://cloud.githubusercontent.com/assets/20048529/16228184/c2bfa8fa-37b5-11e6-959f-55477f43047e.PNG)

**Comment by oroulet** [comment]
OK. I think next step is to install wireshark and record 2 sessions, one with uaexpert and one with python-opcua while reading the same node. Then attach the result to the bug. Then we will see if we send something different than uaexpert

**Comment by zerox1212** [comment]
Now that I see your server structure, why not call the ReadVar method with python instead of ```get_value()``` ?

**Comment by davidschranz** [comment]
I will have access to the failing machine next Friday. Attached are already the Wireshark recordings including the test scripts of the machine that works. Thank you both for your support.




[Server1 Results.zip](https://github.com/FreeOpcUa/python-opcua/files/327238/Server1.Results.zip)

**Comment by oroulet** [comment]
We need a record of a get_value from uaexpert too on the machine that does not worl. Simply click refresh on the attribute view.

**Comment by davidschranz** [comment]
In short, the problem of the failing machine was on the server side.
UAExpert also failed on the get_value when added as a custom node. The last time I only tested the call_method with it. The workaround to use the call_method on the python side worked.
Thank you both @oroulet and @zerox1212 to get my problem resolved!

**Comment by destogl** [comment]
After last comment seams solved.
