### ISSUE TITLE
_encrypt_password() function does not return anything

### ISSUE THREAD

**Issue by hunterjackson** [FreeOpcUa/python-opcua#219]
Based on the error shown below the `_encrypt_password()` function is expected to return `data` and `uri`. I will work on fixing this and making a PR.

```
_add_user_auth(self, params, username, password)
    417             params.UserIdentityToken.EncryptionAlgorithm = ''
    418         elif self.server_url.password:
--> 419             data, uri = self._encrypt_password(password, policy_uri)
```

**Comment by oroulet** [comment]
Looks like we have bunch of errors around password stuff. We should add tests for this...
