### ISSUE TITLE
Question about server event

### ISSUE THREAD

**Issue by TheAtlantis** [FreeOpcUa/python-opcua#226]
Hi, 

I would like catch client item subscribe event on my server.
How catch this event ?

Thank you for you help.

Michel

**Comment by oroulet** [comment]
No code for that. By I guess you can add a callback in create subscription
in subscription service class

**Comment by oroulet** [comment]
And send PR

**Comment by TheAtlantis** [comment]
Thank for your fast reply. 
I try this and PR if the solution is fine.
