### ISSUE TITLE
populating address space with an xml file and use its variables.

### ISSUE THREAD

**Issue by brochet** [FreeOpcUa/python-opcua#246]
Hello,

Thank you very much for your python-opcua client&server examples.
I'm a beginner in python and opc ua.
I created a server and I had generated an xml file to populate my address space (I use UaExpert Client).
![capture](https://cloud.githubusercontent.com/assets/20514120/16910753/ab53a984-4cda-11e6-89c4-56bd3107cbda.PNG)
I used in my python code: server.import_xml("my_file.xml") to import all nodes.
Now I want to use the nCommand variable in my python code, but I tried lots of different things to retrieve this variable in my code and I did not succeed.
For example, when I change the value of this variable with uaExpert client, I want to retrieve this value in my code. 
a view of my variable in my xml file:
![capture2](https://cloud.githubusercontent.com/assets/20514120/16910969/10418a72-4cdc-11e6-8f89-e3b2fde95767.PNG)

Thanks in advance for your help.

**Comment by zerox1212** [comment]
Can you post your code which tries to get the value of nCommand?

**Comment by brochet** [comment]
I read the xml file directly with minidom, but it's not the good way because I want to read the value when the UaExpert client  change this value.
![capture3](https://cloud.githubusercontent.com/assets/20514120/16941284/6ec34816-4d8f-11e6-91f4-721c49ec4fe3.PNG)

**Comment by oroulet** [comment]
read the server example file for example and you should be able to figure out.
if you know the path:
objects = server.get_objects_node()
mydevice_var = objects.get_child(["0:controller", "0:state", xxxxxxx]) 
if you  know the node id:
server.get_node(mynodeid)

**Comment by brochet** [comment]
I have an error. @oroulet it's possible to explain me how to fulfil get_child(["0:controller", "0:state", xxxxxxx]) in my case? 
![capture4](https://cloud.githubusercontent.com/assets/20514120/16942472/7abcdc7a-4d96-11e6-8787-7eb6adb5a529.PNG)

**Comment by oroulet** [comment]
your sample does not show the path but it shows the node id so just write
var = server.get_node("ns=2;i=9002")
then look at the var object

**Comment by brochet** [comment]
Yes of course, but I don't know what to put in the place of : "0:controller", "0:state" and xxxxxxx to read the value equals to 10 in this case.

**Comment by oroulet** [comment]
something like 
objects.get_child(["0:PNC1_sml", "0:DeviceState", "0:Main", "1:ctrl", "1:nCommand"])
0 is the namespace of the used browsename, seems to be 1 or 0 in you example but your screenshort does show it. it might be different for every node

**Comment by oroulet** [comment]
and get value with var.get_value()

**Comment by brochet** [comment]
Thank you very much !
