### ISSUE TITLE
Initial `publish` call twice

### ISSUE THREAD

**Issue by georgschoelly** [FreeOpcUa/python-opcua#264]
In [opcua/common/subscription.py][1] `publish()` get's called twice and we have two publish requests in the air at any time. This seems like a mistake to me, afaik one publish request should be enough.

This behavior dates all the way to the beginning: ec747788ba98bf87f0d4b4afb054ea8a85f03856

Is there a reason for this? If yes, then it should probably be commented, if not, let's just delete it.

 [1]: https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/common/subscription.py#L89

**Comment by oroulet** [comment]
We create a buffer of publish request. All clients I have seen do this and this is OK with spec
