### ISSUE TITLE
Timestamps in Subscription handler

### ISSUE THREAD

**Issue by cedricleroy** [FreeOpcUa/python-opcua#265]
This may be the same than #202. Looks like timestamps cannot be retrieved in _datachange_notification_. I did try the following:
```python
def datachange_notification(self, node, val, data):
    print data.monitored_item.Value.SourceTimestamp
    print data.monitored_item.Value.ServerTimestamp
    print data.monitored_item.Value.Value
    print data.monitored_item.Value.StatusCode
```
And got None for _SourceTimestamp_ and _ServerTimestamp_, though I get timestamps when pulling data manually without going through the event handler.

**Comment by oroulet** [comment]
Look at the MonitoredItem which is sent while subscribing. Maybe it does not request timestamps. If so, this is an error

**Comment by cedricleroy** [comment]
In _create_monitored_items_:
```python
params.TimestampsToReturn = ua.TimestampsToReturn.Neither
```

It works properly using Both.

**Comment by oroulet** [comment]
Can you send a PR?

**Comment by maljac** [comment]
Can we close this?
