### ISSUE TITLE
[help] Block Subscription Callbacks / Publishing Interval

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#288]
My application needs to work on some data held in multiple objects. These python objects mirror UA objects and are kept in sync via subscription.

I need to work on the data in these objects without the subscription thread changing the data during some heavy calculation loops.

What is the best way to block/ignore the subscription callback to ensure my data is consistent?

**Comment by oroulet** [comment]
In theory it is possile to pause subscriptions but this is not implemented.
I think a correct solution is to take a snapshot of your values and use that for computation.

**Comment by oroulet** [comment]
btw if you change things in exporter or modeller, make a PR asap so we do not make double work or get issues merging

**Comment by zerox1212** [comment]
If I start anything I will make a PR.

**Comment by zerox1212** [comment]
I will manually copy the values i'm working on to avoid this issue. In the future it would probably good to implement this. Especially if we want to generate python objects from UA objects and keep the synchronized.

**Comment by zerox1212** [comment]
I have a new related question. When using the server do internal subscriptions obey the publishing interval?
