### ISSUE TITLE
Server.import_xml provides no information on failure

### ISSUE THREAD

**Issue by cpisbell-vasig** [FreeOpcUa/python-opcua#294]
If the XML file contains something that Server.import_xml does not like, it provides no indication as to what the problem is and where it is in the file. It would be very helpful to have a reason and a line number reported.

**Comment by oroulet** [comment]
Agree :-) patch welcome

**Comment by zerox1212** [comment]
Thanks to @oroulet import has some limited logging now. Is it enough to solve your issue?
https://github.com/FreeOpcUa/python-opcua/commit/64396cf9982edabd7f411de1aa32f2c8a0946e06
