### ISSUE TITLE
Secure Channel Reconnect Timing

### ISSUE THREAD

**Issue by dadkins1** [FreeOpcUa/python-opcua#301]
The secure channel is reconnecting every 42 seconds even though the timeout for the secure channel is set to 1 hour. If the intent is to reconnect at 0.7 times the interval (as stated in the comment in client.py:352), the reconnect should instead be every 42 minutes.

**Comment by oroulet** [comment]
Have a look. The code is very simple

**Comment by dadkins1** [comment]
Looks like my server was coming back with a revised timeout of 60 seconds, which explains why the reconnect was so short. Thanks!

**Comment by oroulet** [comment]
Thanks for the feedback!
