### ISSUE TITLE
Dead historizing methods in server

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#315]
When I was working on some other things I saw that this is still in server.py:

``` python
    def historize_node(self, node):
        self.iserver.enable_history(node)

    def dehistorize_node(self, node):
        self.iserver.disable_history(node)
```

These don't work, and in the examples historizing is done by calling `iserver` methods directly.
`server.iserver.enable_history_data_change(myvar, period=None, count=100)`

Should we delete these or fix them to reference correct `iserver` methods?

**Comment by destogl** [comment]
It would be the best to fix to reference correct methods and also that we have tests for them...

**Comment by zerox1212** [comment]
If we fix them it's only for user convenience. The server method is just going to call the iserver method with the same parameters.

If I get time I will fix it and update tests.

**Comment by zerox1212** [comment]
Fixed in https://github.com/FreeOpcUa/python-opcua/pull/353
