### ISSUE TITLE
print "cryptography is not installed, use of crypto disabled"

### ISSUE THREAD

**Issue by jk987** [FreeOpcUa/python-opcua#346]
I can live with this but somebody might be upset:

In client.py there is a print "cryptography is not installed, use of crypto disabled" when import doesn't succeed. (And it doesn't succeed because I can't install cryptograhy because it requires MS Visual C++ 9.0 and I'm to lazy to solve this, I don't need cryptography.)

Doesn't it need to be "print"?
Couldn't be there some logging?

**Comment by zerox1212** [comment]
Make a PR to move it to logger, I don't think it would be a problem.

**Comment by jonemo** [comment]
This has been addressed in https://github.com/FreeOpcUa/python-opcua/pull/528
