### ISSUE TITLE
Datavalue

### ISSUE THREAD

**Issue by mparini** [FreeOpcUa/python-opcua#347]
I read node:
var=client.get_node("ns=2;i=72530").get_children()[2].get_value()
var is:
[DataValue(Value:Variant(val:[Variant(val:0,type:VariantType.Byte), Variant(val:False,type:VariantType.Boolean), Variant(val:LocalizedText(Encoding:3, Locale:it, Text:f99121; No ->  OPC UA Server),type:VariantType.LocalizedText), Variant(val:ArburgSuperuser,type:VariantType.String), Variant(val:NumericNodeId(ns=2;i=329930),type:VariantType.NodeId), Variant(val:0,type:VariantType.UInt32)],type:VariantType.Variant), StatusCode:StatusCode(Good), SourceTimestamp:2016-10-27 05:55:55, ServerTimestamp:2016-10-27 15:19:06)]

How can I read value of Text:   es. f99121; No ->  OPC UA Server
How can I extraxct value from DataValue?

Thanks
Massimo Parini

**Comment by zerox1212** [comment]
OPC UA generally returns UA objects, not a native value. You need grab your data from the object.
`my_text = var.Value.Value.Text` or something like that.
