### ISSUE TITLE
How to write variables in current implementation from extarnal aplication

### ISSUE THREAD

**Issue by destogl** [FreeOpcUa/python-opcua#37]
Hi,

I just wanted to set some variables from external application but was getting error regarding access rights. Currently, on creation of variables and properties they are defined to be only read, but what if one would like to write this variables/properties from outside? Should current implementations be extended or there is some other way to set user-rights for every node?

**Comment by oroulet** [comment]
Set_writable on Node object?

**Comment by destogl** [comment]
Thanks! Didn't look deeply...

**Comment by oroulet** [comment]
If you an idea to document it better.. Maybe add it to example. We also
need to split example files

**Comment by destogl** [comment]
I just added a line in example-server with this. See. #34
