### ISSUE TITLE
Booleans converted to ints

### ISSUE THREAD

**Issue by drakes00** [FreeOpcUa/python-opcua#38]
Hello,

As in python ```isinstance(True,int) == True```, all boolean values passed to a Variant will be converted to Int64 when going through Variant._guess_type at line 741 of python-opcua/opcua/uatypes.py.

Is this wanted to avoid the use of booleans ?

Best,
Maxime

**Comment by destogl** [comment]
I would say it is error, I just also has it. That's why I had to make it "dirty" [here](https://github.com/FreeOpcUa/python-opcua/pull/35/files#diff-9a04e0625aca432894645155aefd62f6R37). Let me just take a look...

**Comment by destogl** [comment]
#39 should solve your problem

**Comment by drakes00** [comment]
Thanks a lot :-)

**Comment by destogl** [comment]
@oroulet Can I merge?
