### ISSUE TITLE
Fail to read more than 50 Tags in python-opcua client application with TIA Portal OPC UA Server simulator

### ISSUE THREAD

**Issue by bhoomil-avch** [FreeOpcUa/python-opcua#385]
Hi,
I have found one issue with python-opcua client APIs.
Please go through the following link as I already discussed this bug on FreeOpcUa Google Group,
[https://groups.google.com/forum/#!msg/freeopcua/r-OasG4eshg/rhWSmxplBQAJ](url)

The issue is in the following call stack.
![callstack_tags](https://cloud.githubusercontent.com/assets/6021881/21136262/f2bfaa22-c14a-11e6-8efa-c929ba02057d.PNG)

**Comment by zerox1212** [comment]
As a possible workaround you could see if TIA Portal UA server has a setting to turn off truncating browse results.

**Comment by bhoomil-avch** [comment]
I'm new at TIA Portal currently,
till now I don't find anythings regarding "turn off truncation"
I'm surprise that why uaexpert.exe gives me the perfect result.
As you said that go with workaround by turning off truncation off at server side but are there any workaround possible at client side? because ultimately problem is in the client APIs

**Comment by oroulet** [comment]
Python client must be fixed as explained in mailing list. This is not
difficult

**Comment by oroulet** [comment]
https://github.com/FreeOpcUa/python-opcua/pull/386

**Comment by bhoomil-avch** [comment]
Thanks.,, the changes you have done is now working fine.
