### ISSUE TITLE
Strong Typed Variables Don't Pass Validation

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#40]
When another OPC UA server is the client to python opcua "Strong Typed" variables don't pass validation.

I am using TOP Server OPC UA client to my python OPC UA server and it only adds variables with no ua type.

From the example-server, this will be thrown by TOP Server:
```
Date        Time         Level        Source                               Event
10/4/2015    5:09:47 PM  Warning      OPC UA Client                        Tag 'myStronglytTypedVariable' on device 'Channel1.Device1' was not imported. The item failed validation.
```

I don't know what validation is taking place. Is there any way to troubleshoot this?

Edit: I did more research. Oddly enough other clients (such as UaExpert) doesn't have any problems. If I manually add this tag to TOP Server and manually set the data type it also seems to work. It could be a problem with TOP Server object import. If there isn't anything we can do this issue could be closed.

**Comment by oroulet** [comment]
as long as this product does not report a better error, it is hard to find
out what is happening..

**Comment by oroulet** [comment]
I installed kepware and got something similar, not all variables are accepted by kepware client....

**Comment by kevincolyar** [comment]
@zerox1212 Having the same issue.  If I set the type, float for example:

```python
return ua.Variant(float(value), ua.VariantType.Float)
```
 my TOP server sets it as a Float Array.

Have you found a good workaround without having to manually set the datatypes in TOP Server?

**Comment by oroulet** [comment]
can it be an issue with ValueRank attribute? try set it to -2, -1, 0, 1, etc

**Comment by kevincolyar** [comment]
Where would I set the ValueRank?  Here's what I'm doing now:

```python
folder.add_variable(self.namespace, name, ua.Variant(float(value), ua.VariantType.Float)
```

**Comment by oroulet** [comment]
Your call return a node object. Then call node. Set_attribute
(ua.attributeids.valuerank, data value(-1, ua.varianttype.XXX))

**Comment by kevincolyar** [comment]
Thanks, that was it:

```python
node.set_attribute(ua.AttributeIds.ValueRank, ua.DataValue(-1))
```

**Comment by oroulet** [comment]
Does it also work with -2?
-1 means scalar while -2 can be anything

**Comment by kevincolyar** [comment]
-1 : Correctly results in Float (Timestamp hour is offset)
-2 : Incorrectly results in Float Array (Timestamp is correct)

**Comment by oroulet** [comment]
ok then we know it. I pushed a change to master
https://github.com/FreeOpcUa/python-opcua/commit/64e049595105c46600316e6ff2e127a329c6a219
. Now we set better default value for valuerank automtically at at variable
creation

**Comment by kevincolyar** [comment]
Thanks so much.  Works perfectly and the timestamps are correct now.
