### ISSUE TITLE
Custom event properties aren't send in example server-events

### ISSUE THREAD

**Issue by bitkeeper** [FreeOpcUa/python-opcua#414]
While fixing an exception in `examples/server-events.py` in PR #413 , I noticed that in UaExpert not all properties of the custom event where received/transmitted.

Should the following fragement of the example work ?:
```python
etype = server.create_custom_event_type(idx, 
                                              'MyFirstEvent', 
                                              ua.ObjectIds.BaseEventType,
                                              [('MyNumericProperty', ua.VariantType.Float), 
                                               ('MyStringProperty', ua.VariantType.String)])
evgen = server.get_event_generator(etype, myobj)
...
evgen.event.Message = ua.LocalizedText("MyFirstEvent %d" % count)
evgen.event.Severity = count
evgen.event.MyNumericProperty = count
evgen.event.MyStringProperty = "Property " + str(count)
evgen.trigger()
```

Output of UaExpert:

Both Events are received:
![image](https://cloud.githubusercontent.com/assets/1525169/23552246/2379f4ba-001b-11e7-85c1-d83b3252849d.png)

Looks like only the BaseEventType properties are send:
![image](https://cloud.githubusercontent.com/assets/1525169/23552170/d6f693be-001a-11e7-91f6-d2754d48a424.png)

**Comment by oroulet** [comment]
uaexpert does not check what properties an event has and only ask for the properties of BaseEventType. It might be that it does not manage to find the event definition, but I do not think so. It is a limitation of uaexpert

**Comment by bitkeeper** [comment]
Found it, just my fault! 
You have to configure the UaExpert to show more then the basic event events:

- In the UaExpert configuration of the EventView 
- Click on '>'  at SimpleEvents 
- Enable your own event type or one or more properties of your event (or just select all at the checkbox at SimpleEvents)

![image](https://cloud.githubusercontent.com/assets/1525169/23554859/13e41b5a-0027-11e7-8eb7-ca10ed72be65.png)

**Comment by oroulet** [comment]
thanks for the info
