### ISSUE TITLE
Implement support for password in client

### ISSUE THREAD

**Issue by mertz3hack** [FreeOpcUa/python-opcua#42]
Looking for help understanding a connection issue.
I am trying to connect to a machine hosted opc ua server using
    <code>client = Client("opc.tcp://user:password@192.168.15.30:4880/Arburg")</code>

I am getting the following error and am not sure if this is something I am doing or if this is not supported yet.

<code>Traceback (most recent call last):
  File "example-client.py", line 41, in <module>
    client.connect()
  File "C:\opcua\opcua\client.py", line 111, in connect
    self.activate_session()
  File "C:\opcua\opcua\client.py", line 199, in activate_session
    params.UserIdentityToken.Password = bytes(self.server_url.password)
TypeError: string argument without an encoding
WARNING:opcua.binary_client:Received an error message type
WARNING:opcua.binary_client:MessageAbort(error:StatusCode(BadInvalidArgument), reason:)
</code>

**Comment by oroulet** [comment]
Yes, there is an issue with the password implementation. I do not know how to encode it. it is probably just a matter of reading the doc , though.... so help welcome here

**Comment by mertz3hack** [comment]
Should this issue be combined into the other issue?

**Comment by oroulet** [comment]
yes there is already an issue on this https://github.com/FreeOpcUa/python-opcua/issues/23 . you are welcome to try to solve this :-)
look at line 199 in client.py. We need to encrypt password and set correct encryption in line under.

To find out what should be there you can read the opc-ua specification (But I could not find anything) and/or start wireshark, set filter type to opcua,  and connect with a client supporting encryption (uaexpert for example). then do the same with python-opcua and look at the difference in the ActivateSession message

**Comment by oroulet** [comment]
btw what server are you using?

**Comment by mertz3hack** [comment]
I am using an Arburg Injection Molding Machine that hosts its own opc-ua server

**Comment by oroulet** [comment]
That's interesting!. Do you manage to connect if you disable password?

**Comment by oroulet** [comment]
yesterday I registered a session between a client and a prosys server:
server return 2 supported PolicyId: username_basic256 and username_basic128
and security policy URI is set to http://opcfoundation.org/UA/SecurityPolicy#Basic256
when sending password in activateSession it refers to following EncryptionAlgorythm
http://www.w3.org/2001/04/xmlenc#rsa-oaep
I have no idea where the key for the encryption is taken from ...

**Comment by mertz3hack** [comment]
I am not able to disable the password
I will try and watch a session to see how it compares

**Comment by oroulet** [comment]
password and encryption is supposed to be implemented for client now. Can someone test and resport?

**Comment by mertz3hack** [comment]
I am having the worst time trying to get python with pycrypto setup on my new computer.  I will be able to test this out on Wednesday assuming I get pycrypto working.

**Comment by oroulet** [comment]
Master should not use pycrypto but cryptography module... But I am not sure
all patch have been merged

**Comment by oroulet** [comment]
I merged the last patch removing pycrypto ( I hope I did not break to much things for you @alkor !!!). Everything is in place for password encryption, but it might no be implemented yet. I am waiting for @alkor to merge the rest of his crypto stuff

**Comment by mertz3hack** [comment]
No errors about pycrypto anymore.

![test](https://cloud.githubusercontent.com/assets/4985248/12051760/d28d1bf0-aed5-11e5-9f71-8a9de6387956.png)
![code](https://cloud.githubusercontent.com/assets/4985248/12051762/d4e570e6-aed5-11e5-8030-d17011f9205a.png)

**Comment by oroulet** [comment]
Now I tested password encryption and it works against prosys server. Thanks @alkor

**Comment by alkor** [comment]
That's great!

**Comment by joaopmrod** [comment]
I'm trying to connect using this: opc.tcp://admin:password@localhost:4096 and  I get this error:

showing error:  name 'uri' is not defined 1.

If I enable anonymous access I can do it.

**Comment by mertz3hack** [comment]
@joaopmrod is the error you are getting similar to the one in this issue #135 
unfortunately in that specific case I am not able to enable anonymous access
