### ISSUE TITLE
Code generator broken ?

### ISSUE THREAD

**Issue by bitkeeper** [FreeOpcUa/python-opcua#440]
Today I wanted to make some changes to the codegenerator output, but the generator doesn't work.

Because the generator isn't part of the current tests; Can it be that the code generator (schemas/generate_address_space.py:CodeGenerator) is broken due changes to the xmlparser last year ?

**Comment by oroulet** [comment]
Can be...  Should not be hard to fix anyway

**Comment by oroulet** [comment]
just checked and yes it is broken. I kind of remember that I had to change that to a list to preserve order. should be same data so easy to fix. hopefully....

**Comment by bitkeeper** [comment]
Was indeed easy to fix. Because I not really familar with this piece of code can you review PR #442 and check if the output of the generator is still what you expect ?

**Comment by zerox1212** [comment]
Would be great if you could add a few doc strings on how the code generator works. I tried to use it a long time ago to generate part 14 of specification and couldn't figure out how to get it to run...
