### ISSUE TITLE
Confirm that creating monitored items or subscriptions

### ISSUE THREAD

**Issue by aquari89** [FreeOpcUa/python-opcua#467]
Hello, All.

Among the server functions,
Is the ability for the server to verify that client tools(ex: UaExpert) have created monitored items or subscriptions?

If the python-opcua server part has that capability, can you tell me what it is?

**Comment by zerox1212** [comment]
Do you want a list of clients, or a list of nodes that have subscriptions?

**Comment by aquari89** [comment]
I want to know a list of nodes that have subscriptions.

Can I know if a particular node has a subscription, not an entire node list?

**Comment by zerox1212** [comment]
I would have to look or you should wait for @oroulet . As far as I know there is no method on the node for checking this. You would probably have to dig into the server's session object or maybe the internal address space dict.

**Comment by destogl** [comment]
this is stored in internal address space dict. Theoretically is possible and should be relatively easy to implement it.

@aquari89 how would look the call to the function to check this?

**Comment by oroulet** [comment]
Knowing if a node has subscription is cheap, knowing which subscription is harder. Knowing which client need an api change

**Comment by aquari89** [comment]
@zerox1212 @destogl @oroulet 
Thank you for your reply!

**Comment by destogl** [comment]
This seams to be solved.
