### ISSUE TITLE
There are pip installation?

### ISSUE THREAD

**Issue by NervenCid** [FreeOpcUa/python-opcua#468]
Hello:

I'm new in OPC and i find this repository, i see that you are using Python. I searched this package in pip and i found these options:

opcua-client (0.5.0)     - Minimal OPC-UA Client GUI
freeopcua (0.90.3)       - Pure Python OPC-UA client and server library
opcua-modeler (0.4.0)    - OPC-UA Address Space Modeler
opcua-widgets (0.4.0)    - OPC-UA Widgets
opcua-webclient (0.0.6)  - A OPCUA web client, implemented by Python.

Wich one is your package?

Thank you

**Comment by zerox1212** [comment]
freeopcua (0.90.3) - Pure Python OPC-UA client and server library is the core client and server library.
