### ISSUE TITLE
create_monitored_items

### ISSUE THREAD

**Issue by ruderjack** [FreeOpcUa/python-opcua#469]
@oroulet,
Although the issue  #178 is closed for a long time, I still have problems to create a monitored item at the client.
Can you please make a "MonitoredItem" example?
Thanks in advanced

**Comment by oroulet** [comment]
creating a monitoreditem by hand requires a good understanding of UA protocol. If you have that understanding you do not need an example. So most probably you do not want to create a monitoreditem by hand..
