### ISSUE TITLE
Get node by name or ID

### ISSUE THREAD

**Issue by KingUdo** [FreeOpcUa/python-opcua#479]
Hi Everybody,
I'm trying to create Nodes dynamically. Something like this: 
1. I create a list with names
2. The server creates the same number of nodes, as items in the list, with there name being the String in the List
Then later on I would like to be able to edit the value of those nodes. 
I think I should be able to create a certain number of nodes with a simple for loop, and then setting there name to the string in the list. But how can I then access them later on? Is there something like a get_node_by_name() sort of function? I can't seem to find it! Or do you have any other idea how I could solve that problem?
Thanks! And excuse the rather awful English ;-)

**Comment by zerox1212** [comment]
You need to read about OPC UA specification more. Do you want a bunch of child nodes in a folder? Are these nodes part of an object? Do you want an Extension Object so your list is treated like a class?

If you just need child nodes you can add them with a loop like you say and give them a special browse name. After that you have some options, for example you can just keep track of your parent object, and later call `myparent.get_children()` and now you have a list of all your child nodes. Or you can do `myparent.get_child('1:mylistchild')` or something to that affect to get a single child node. Keep in mind doing it this way will not give you "list" behavior as you you don't have an array with the method I describe.
