### ISSUE TITLE
Arburg BadIdentityTokenInvalid

### ISSUE THREAD

**Issue by mparini** [FreeOpcUa/python-opcua#481]
I use opcua python with 4 machine Arburg with no problem.

Now arrive new one.

I use the same 
client=opcua.Client("opc.tcp://host_computer:marca@192.101.5.30:4880/Arburg")
client=opcua.Client("opc.tcp://host_computer:marca@192.101.5.22:4880/Arburg") new one

The user name and password is the same. But for the new one we can't connect.

If I try with dataFEED or UaExpert I have no problem.
![image](https://user-images.githubusercontent.com/5786733/28858933-8a03e49c-7754-11e7-8611-dc9be1839fd5.png)
![image](https://user-images.githubusercontent.com/5786733/28859125-daf697a4-7755-11e7-8a59-a7f86f18523c.png)

![image](https://user-images.githubusercontent.com/5786733/28858949-9bb9f884-7754-11e7-8b88-876007153d4f.png)

![image](https://user-images.githubusercontent.com/5786733/28859061-67ca5c98-7755-11e7-99b5-8e3fa0806031.png)

In Python:
![image](https://user-images.githubusercontent.com/5786733/28859331-fd36e084-7756-11e7-9ac2-6ad52a93ba59.png)

If I use FreeOpcUa Gui Client the same error, the query server capability:
![image](https://user-images.githubusercontent.com/5786733/28859715-42198e02-7759-11e7-9723-d8194524a8be.png)

If I use uadiscover:
![image](https://user-images.githubusercontent.com/5786733/28859040-2d52fec6-7755-11e7-952d-cb1e9eea3545.png)

Any idea.
Thanks 
Massimo Parini

**Comment by oroulet** [comment]
Looks like you need to for wireshark and record a session from uaexpert and one from python. Then we can try to spot a difference..

**Comment by mparini** [comment]
I try. The different maybe is uaexpert and Datafeed send a certificate. The comunication is more complex that python.


[pcapng.zip](https://github.com/FreeOpcUa/python-opcua/files/1194731/pcapng.zip)



Massimo

**Comment by mparini** [comment]
I find the problem:
params.UserIdentityToken.EncryptionAlgorithm = ''
in
params.UserIdentityToken.EncryptionAlgorithm = None

in opcua/client/client.py
change:
  def _add_user_auth(self, params, username, password):
        params.UserIdentityToken = ua.UserNameIdentityToken()
        params.UserIdentityToken.UserName = username
        policy_uri = self.server_policy_uri(ua.UserTokenType.UserName)
        if not policy_uri or policy_uri == security_policies.POLICY_NONE_URI:
            # see specs part 4, 7.36.3: if the token is NOT encrypted,
            # then the password only contains UTF-8 encoded password
            # and EncryptionAlgorithm is null
            if self.server_url.password:
                self.logger.warning("Sending plain-text password")
                params.UserIdentityToken.Password = password
            **params.UserIdentityToken.EncryptionAlgorithm = None #''
        elif self.server_url.password:
            data, uri = self._encrypt_password(password, policy_uri)
            params.UserIdentityToken.Password = data 
            params.UserIdentityToken.EncryptionAlgorithm = uri
        params.UserIdentityToken.PolicyId = self.server_policy_id(ua.UserTokenType.UserName, b"username_basic256")

Thanks
Massimo Parini

**Comment by oroulet** [comment]
Are you making a PR? Otherwise leave bug open. If there is a bug we need to fix it
