### ISSUE TITLE
node-red-contrib-opcua cannot browse python-opcua server

### ISSUE THREAD

**Issue by brubbel** [FreeOpcUa/python-opcua#486]
Hi,

The node-red [opcua browser](https://www.npmjs.com/package/node-red-contrib-opcua) does not return any results when connecting to the python-opcua server.

This is caused by the ReferenceTypeId:TwoByteNodeId in the [BrowseDescription](https://github.com/FreeOpcUa/python-opcua/blob/273580aa35b44413833f4acd8f958b871140a804/opcua/ua/uaprotocol_auto.py#L6041).

While UaExpert for example sets the ReferenceTypeId to i=33 ([HierarchicalReferences](https://github.com/FreeOpcUa/python-opcua/blob/273580aa35b44413833f4acd8f958b871140a804/opcua/ua/object_ids.py#L39)), the node-red browser sets this BrowseDescription field to i=0.

From [unified-automation.com](http://documentation.unified-automation.com/uasdkhp/1.0.0/html/structua__browsedescription.html
) I read:
> _reference_type_id_
> Specifies the NodeId of the ReferenceType to follow.
> Only instances of this ReferenceType or its subtypes are returned.
> If **not specified**, all References are returned and includeSubtypes is ignored.

I understand '**not specified**' as setting the ReferenceTypeId (binary data) = 0, which is then read by python-opcua as TwoByteNodeId(i=0) instead of None or equivalent.

This then further impacts the [ViewService](https://github.com/FreeOpcUa/python-opcua/blob/273580aa35b44413833f4acd8f958b871140a804/opcua/server/address_space.py#L99), which rejects all results (0 != 32 NonHierarchicalReferences, 0 != 33 HierarchicalReferences) instead of allowing all results from what I understand should be the correct behaviour.

What would be the best place to solve this? uaprotocol_auto.py does not seem a good place for manual changes, however TwoByteNodeId(i=0) instead of None is also not correct.

PS: when I intercept the TwoByteNodeId(i=0) case in the [ViewService](https://github.com/FreeOpcUa/python-opcua/blob/273580aa35b44413833f4acd8f958b871140a804/opcua/server/address_space.py#L99), browsing works in node-red-contrib-opcua.

**Comment by oroulet** [comment]
Thanks for the detailed report. As far as I remember I=0 is called a null
nodeid and you cannot set it as more null than that. Catching the I=0 case
in view service sounds like the correct fix. Can you send a PR?
