### ISSUE TITLE
How to access variables using node id ?

### ISSUE THREAD

**Issue by SAndrew27** [FreeOpcUa/python-opcua#496]
I have an `OPCUA server` and I am trying to connect to it. I have successfully installed its opcua client gui and able to browse to it.This is how the address space looks like:

   
    Root                         0:Root                          i=84
    |->Objects                   0:Objects                       i=85
      |->Server                  0:Server                        i=2253
      |->Data Set                2:Data Set                      ns=2,i=50001
      |->PLC                     4:PLC                           ns=4,i=20000
       |->Modules                6:Modules                       ns=6,i=1000
         |->Data PV              6:Data PV                       ns=6,s=::AsDataPV
           |->Var1               6:Var1                          ns=6,s=::AsDataPV:Var1
           |->Var2               6:Var2                          ns=6,s=::AsDataPV:Var2
           |->Var3               6:Var3                          ns=6,s=::AsDataPV:Var3
           |->Var4               6:Var4                          ns=6,s=::AsDataPV:Var4
           |->Var5               6:Var5                          ns=6,s=::AsDataPV:Var5

I want to get the values of `var1, var2, var3 ,var4, var5` using client library. How can I extract its values by using their node ids.

Thanks

**Comment by zerox1212** [comment]
What do you mean extract? The client GUI displays variables and their values. If you want to get the variable values and do something with them you will have to use the client library. There are many examples for this.

**Comment by SAndrew27** [comment]
Yes how to use the library to extract the values. Can you please show me an example

**Comment by zerox1212** [comment]
Please take a look at the repo and at least try to make it work on your own before making an issue.

https://github.com/FreeOpcUa/python-opcua/blob/master/examples/client-minimal.py

**Comment by SAndrew27** [comment]
HI
I am able to get the root node and its children too.

client = Client("opc.tcp://192.168.111.231:4840")
client.connect()
root = client.get_root_node()
print(root.get_children())

This print out the its children with node it i=84,i=85,i=86. I want to know How to proceed further and access the node using i=84.

**Comment by zerox1212** [comment]
You can keep calling `x.get_children()` on child nodes until you have the list of nodes you want. Or you can get a node directly by it's ID as shown in the examples.

`var = client.get_node("ns=6;s=::AsDataPV:Var1")`

**Comment by amisha218** [comment]
how to write values from your python client to opc scout?

**Comment by oroulet** [comment]
@amisha218 please stop hijacking old bug reports. If you have a question, create a new bug report and give enough information. Read this for example: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports
