### ISSUE TITLE
Malformed OpenSecureChannelResponse

### ISSUE THREAD

**Issue by Stasik0** [FreeOpcUa/python-opcua#51]
Hey guys,

we got a user who tested our open62541 client with pyhton server (and it did not work).

As far as I see in wireshark, the OpenSecureChannel response is malformed (and our client returns a decode error). However UaExpert seems to ignore this problem and just carries on, however a malformed packet is there.

The wireshark capture can be found here: http://s000.tinyupload.com/index.php?file_id=50188691273227621360 (minimal-server.py server runs on port 16664).

A screenshot is shown below:

![screenshot from 2015-10-29 08 45 05](https://cloud.githubusercontent.com/assets/469170/10812764/c2ad8ba8-7e19-11e5-9aa8-f597606ef2f9.png)

Any idea what's the reason?

**Comment by oroulet** [comment]
I downloaded the file and I cannot see any malformed packet. What version of python-opcua do you use? (But nobody has touched parsing files for  several months so it should not change much),  and what version of wireshark? I have wireshark 1.12.7
it looks like the security token is wrong on your screenshot. Wireshark says channelId 16 and tokenId 15 in the log I downloaded from you in second response

**Comment by Stasik0** [comment]
just cloned master
From what I see the channel and token id have a different byte-order so 268435456 is actually a flipped 16, i got wireshark 1.10.6, so i will try to update wireshark, standby

**Comment by oroulet** [comment]
Are you on ARM? I only tested on an intel prosessor. I tested a few months ago on a raspberry and everything seemed to work. But I may have missed somehting...

**Comment by Stasik0** [comment]
nope, intel i5 here.... new wireshark shows no errors (this is spooky)... I will probably have to dig into our code :(

**Comment by oroulet** [comment]
>> I will probably have to dig into our code :(
Exactly opposite feeling here :-)

**Comment by Stasik0** [comment]
okay, it was our problem... due to a bug: https://github.com/acplt/open62541/commit/bed4376400e14601195a2c474bcaf9238d0f3759, we did not decode the inner status code, and introduced a shift into the decoding which resulted in martian string lengths. thank you for help
