### ISSUE TITLE
Advantages / Disadvatages of subscription

### ISSUE THREAD

**Issue by GregorPi** [FreeOpcUa/python-opcua#512]
Hello,

as I was not able to find the answer to my question on google, I want to try and ask for you for your professional opinions :)

I know that OPC UA supports two kinds of ways to communicate data between the server and client. One method is subscription (data is only sent if the value changed) and the other one is cyclic (data is sent in a fixed period).

I was now wondering what the advantages and disadvantages of these methods are.

It would be nice if we could collect some points.
Please let me know if I forgot a method or wrote something wrong.

Thanks!

**Comment by oroulet** [comment]
one method is called pooling, this other publish/subscribe. You can find millions of papers on this on the net.
