### ISSUE TITLE
Unpacking Primitive arrays is slow

### ISSUE THREAD

**Issue by brubbel** [FreeOpcUa/python-opcua#518]
Possibly related to https://github.com/FreeOpcUa/python-opcua/issues/514

Using list comprehension for array unpacking is very slow, for example when reading OPC arrays from history. Profiling narrows it down to the following lines:
https://github.com/FreeOpcUa/python-opcua/blob/9e5a26a97f1079a5db1f55b365411c5e2b5d0317/opcua/ua/ua_binary.py#L203-L207

l'll create a PR with better performance, where reading 1536 x [8192] arrays from history drops from 60 to <6 seconds.

**Comment by oroulet** [comment]
Any help/proposition on this is welcome

**Comment by brubbel** [comment]
Thanks, could you also restart the checks in the above PR? Travis seems to fail at random points, which I suspect is due to timeouts while running the tests.
