### ISSUE TITLE
Implement rsa-oaep password encryption also for the binary client

### ISSUE THREAD

**Issue by fvacek** [FreeOpcUa/python-opcua#523]
Some OPC-UA servers refuses ActivateSession with unencrypted password

**Comment by fvacek** [comment]
I think that python client has it implemented already

**Comment by oroulet** [comment]
What is the issue if we already have it implement?

**Comment by fvacek** [comment]
I have found this  python-opcua/opcua/crypto/uacrypto.py and #125

**Comment by fvacek** [comment]
> What is the issue if we already have it implement?

Because it is not implemented for c++ binary client

**Comment by oroulet** [comment]
Then the bug report should be created in c++ project ;-). And yes there is no support for encryption in c++ (+many fundamental limitations)

**Comment by fvacek** [comment]
sorry, my fault, I'll move issue to correct project
