### ISSUE TITLE
Create folders and variables with NodeId as String instead of numeric

### ISSUE THREAD

**Issue by rjmmartins** [FreeOpcUa/python-opcua#542]
Hi,

Is it possible to set the nodeId type of a variable to String?

I am creating a server to communicate with existing clients, but those clients can only get the nodes by string identifier and not numeric....

**Comment by zerox1212** [comment]
When you create the node just give it a String Node ID.

`my_object.add_folder("s=folder", "folder-browsname")`

**Comment by rjmmartins** [comment]
Thank you so much!
