### ISSUE TITLE
even better command line tools

### ISSUE THREAD

**Issue by oroulet** [FreeOpcUa/python-opcua#57]
This bug report is for brainstorming and ideas for better command line after initial work from @alkor 

General
* node path and url parsing should be shared between tools! it can be the same for  ls, read and write
* move code to tools.py file under opcua, this simplyfies a lot installation and create commands using setup.py
* maybe we should also add this tools to setup.py and install them. calling them lsua and discoverua? (there are allready a bunch og lsusb and other tools on my pc) 

uadiscover
* maybe we should print which server we are connected to in output? (ls commands do not do that!)
* In addition the default discovery port is 4840 (for binary), maybe we should have a default port and even a default url using localhost?
* maybe accept only hostname: "discoverua myhost" using default port

uals:
* should add support for browsename and browsepath? "lsua 2:Objects" or "lsua 2:Objects 3:MyNode". We just nee to test for = or : in name for guessing and/or add option -p for path
* -n (default namespace) then we could just do "lsua opc.tcp://localhost:4841 Objects"
* expose other parameters of Browse (referenceTypeId, nodeClassMask, ...) to filter nodes by type.
* print node type and access rights, probably in style of ls -l

uaread:
* implement
* read value/Attribute for a node
* support HistoryRead (this will require history implementation in client)

uawrite
* implement
* write value/Attribute for a node

uasubscribe:
* subcribe to a node
* -d datachange, -e events

 
other ideas?

**Comment by alkor** [comment]
Yes, I totally agree with your ideas! Here are some more:

lsua:

* expose other parameters of Browse (referenceTypeId, nodeClassMask, ...) to filter nodes by type.
* print node type and access rights, probably in style of `ls -l`

readua:

* support HistoryRead (or should this be a separate tool?)

**Comment by oroulet** [comment]
maybe the commands should start with ua and not end. it increases a lot discoverability in shell with tab:
uals, uaread, uawrite, uasubscribe

**Comment by oroulet** [comment]
started draft of implementation there
https://github.com/FreeOpcUa/python-opcua/commit/cee01ee6062230e99cb66189c4e4423e2f2575bd

**Comment by oroulet** [comment]
added uals. missing some functionality compared to your tool @alkor , feel free to add them

**Comment by oroulet** [comment]
well , I had some time in trains today and implemented most of it
