### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by WangAllen** [FreeOpcUa/python-opcua#577]
======================================================================
ERROR: test_uawrite (tests_cmd_lines.TestCmdLines)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/python/Desktop/python-opcua-master/tests/tests_cmd_lines.py", line 40, in test_uawrite
    s = subprocess.check_output(["python", "tools/uawrite", "--url", self.srv_url, "--path", "0:Objects,4:directory,4:variable2", "1.789"])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', 'tools/uawrite', '--url', 'opc.tcp://127.0.0.1:48530', '--path', '0:Objects,4:directory,4:variable2', '1.789']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 385 tests in 84.315s

FAILED (errors=4)

**Comment by oroulet** [comment]
What is your issue? this is testing code supposed to be run in a node screwed up environment.
