### ISSUE TITLE
OPC UA Security Issues Identified by Kaspersky

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#590]
This is worth a read (there is even a shout out for this python library).
https://securelist.com/opc-ua-security-analysis/85424/

Is anyone familiar with how to apply "fuzzing" to python-opcua?

**Comment by oroulet** [comment]
I am not expecting big issues here from our side. But we need to harden session creation..

**Comment by brubbel** [comment]
I suspect there are a few DOS issues due to the unlimited creation of e.g. subscriptions etc.
Anywhere in the code where objects are added to a collection of items without checking population size.

**Comment by oroulet** [comment]
My comment above was about fuzzing. But yes concerning security..... There is much to do....
