### ISSUE TITLE
Need help  in XML import

### ISSUE THREAD

**Issue by z5239000** [FreeOpcUa/python-opcua#592]
I am new to opc ua,  in the server-custom-object.py file  i just change 
 myobject2_type_nodeid = server.get_root_node().get_child(["0:Types", "0:ObjectTypes", "0:BaseObjectType", "1:MyObjectType"]).nodeid

then it dosen't work , maybe i still don't understand how it works , as i understood , there is UAObjectType names MyObjectType in customobject.xml, so i should get nodeid of MyObjectType.

Thank you very much if someone can answer this question

**Comment by z5239000** [comment]
also strange is, it dosen't show the variable var_should_be_there_after_instantiate under MyCustomObjectA in Uaexpert

**Comment by zerox1212** [comment]
The easiest way to understand how to navigate the structure is to use a GUI based client first, like UA Expert. Then you can look at the tree of nodes (and view the node IDs).

It's also probably better to use an IDE with debugging so you can inspect the objects, because they are often very complicated structures. Don't just add `x.nodeid` and expect it to work.

**Comment by z5239000** [comment]
@zerox1212  Thank you very much , but the structure in costomobject.xml file is very easy to understand, so i think, there should no problem to get the nodeid, and  I have also used  Uamodeler to see the strucktur of the customobject.xml, there should be no problem
![default](https://user-images.githubusercontent.com/34233342/39955383-45ea1476-55ce-11e8-9dba-8825274dc3e0.PNG)

also strange is  that variable var_should_be_there_after_instantiate dosen't shows  under MycustomObjectB or A in UaExpert,  but i can see the object has component of the variable 
![2](https://user-images.githubusercontent.com/34233342/39955474-6094ea02-55cf-11e8-8c1f-8c27913930e6.PNG)

**Comment by z5239000** [comment]
or can you just habe a look at the customobject.xml, whether it is right to get nodeid of MyObjectType by changing myobject2_type_nodeid = server.get_root_node().get_child(["0:Types", "0:ObjectTypes", "0:BaseObjectType", "1:MyObjectType"]).nodeid

**Comment by oroulet** [comment]
What error stack do you get? Print entire stack here

**Comment by z5239000** [comment]
it looks like that the namespace has conflict or something, when i change the Browse name of MyObjectTpye to "2:MyObjectType" in customobject.xml and server-custom-object.py file, then it works,
