### ISSUE TITLE
client.disconnect() keeps background thread running

### ISSUE THREAD

**Issue by jonemo** [FreeOpcUa/python-opcua#599]
Consider this client-side code:

```python
# connect to local test server
from opcua import Client
client = Client(f"opc.tcp://localhost:4848")
client.connect()

# assert that thread is alive
assert client.uaclient._uasocket._thread.is_alive()

# do something with client to confirm that it is in fact connected
_ = client.get_objects_node()

# assert that thread is still alive
assert client.uaclient._uasocket._thread.is_alive()

# disconnect
client.disconnect()

# assert that thread is shut down after disconnect
assert not client.uaclient._uasocket._thread.is_alive() . # <-- Fails with AssertionError
```

Admittedly, this is a very minor issue because the thread will terminate shortly after the call `disconnect()`. I am not entirely sure _why_ the thread terminates, I guess either the socket shutdown or a final arriving message terminate the blocking call to `socket.recv()`. 

Either way, it would be nice if the thread was already gone when `client.disconnect()` returns. Scenarios where this would make a difference:
* If you want to immediately re-connect.
* In my test suite which checks that I'm cleaning up threads properly :)

One possible solution might be to insert `self._thread.join()` as [the last line of `UASocketClient.disconnect_socket`](https://github.com/FreeOpcUa/python-opcua/blob/02b764c9d1aa0441011c9ac553e42d5089d7e371/opcua/client/ua_client.py#L146). If that sounds like a reasonable solution to one of the maintainers, please let me know and I'll make a PR.

**Comment by oroulet** [comment]
Adding join should not be any issue. Not sure why it is not here already...
