### ISSUE TITLE
Alarms no nodes

### ISSUE THREAD

**Issue by LBeaufore** [FreeOpcUa/python-opcua#6]
There appears to be alarms with and without nodes, I only see examples of how to deal with node alarms in PyUAF's "easiest client tutorial". Is there a method to dealing with alarms without nodes?

Thanks!

**Comment by LBeaufore** [comment]
(Posted this in wrong project, sorry)

**Comment by oroulet** [comment]
No pb :-) but you should try python- opcua. At least it does not rely on
third party closed source library!

**Comment by LBeaufore** [comment]
I am actually using it as the primary project right now! We are just exploring multiple options. Thanks!
