### ISSUE TITLE
URNs contain possible typo "freeopcua.github.no"

### ISSUE THREAD

**Issue by jonemo** [FreeOpcUa/python-opcua#600]
I noticed that the URIs [here](https://github.com/FreeOpcUa/python-opcua/blob/cccb122635613eb70b8abcebcabdb6522d981b27/opcua/server/server.py#L81) and [here](https://github.com/FreeOpcUa/python-opcua/blob/cccb122635613eb70b8abcebcabdb6522d981b27/opcua/client/client.py#L104) contain the string `freeopcua.github.no` which looks like a typo of `freeopcua.github.io`. All subdomains of `github.no` are parked domains full of ads.

I know that these are just identifiers and nobody other than people who spend their weekend reading source code will go to that URL, but if this is indeed a typo it should be easy and free of side effects to change, correct?

**Comment by oroulet** [comment]
This is a typo ;-)
