### ISSUE TITLE
Some nodes from standard_address_space_part9 not serializable

### ISSUE THREAD

**Issue by Nebukadneza** [FreeOpcUa/python-opcua#617]
While walking through nodes of the standard address space, part 9, I have discovered some nodes that are broken: Some of their attributes cannot be serialized to binary using `opcua.ua.ua_binary.to_binary(…)`. The nodes affected are all nodes which have a `LocalizedText` as a `Value` attribute. This attribute gets written by `schemas/generate_address_space.py` as follows:
```
attrs.Value = ua.Variant([('Locale', 'en'), ('Text', '<The Text>')], ua.VariantType.LocalizedText)
```
When trying to serialize this Variant (embedded in a `DataValue`), the unpacking-and-serializing-stack eventually ends up in `struct_to_binary`, which will attempt to `for name, uatype in "Locale".ua_types` — but of course `str` doesn’t have a `.ua_types`.

When changing the code-generator by adding the special-case of `LocalizedText` as a Value, thus generating this type of code:
```
attrs.Value = ua.Variant(LocalizedText("<The Text>"), ua.VariantType.LocalizedText)
```
Then serialization works as expected.

The diff on `schemas/generate_address_space.py` is rather small, but before PR’ing anything, I wanted to ask if i understood the problem correctly, and this is the right way of solving it.

Thank & Best Regards
-Dario

**Comment by oroulet** [comment]
Can you create the PR anyway? It is easier to see PR than discussing back
and forth to understand each others

**Comment by Nebukadneza** [comment]
Sorry for the delay!
