### ISSUE TITLE
CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by kleskjr** [FreeOpcUa/python-opcua#621]
uacrypto.py needs an update 
```
../opcua/crypto/uacrypto.py:58: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  hashes.SHA1())                                                                              
../opcua/crypto/uacrypto.py:48: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  hashes.SHA1()   
```

**Comment by hirsche** [comment]
I have the same issue. Is this a bug or wrong package configuration?

**Comment by AndreasHeine** [comment]
The library is deprecated.
Please switch to : [opcua-asyncio](https://github.com/FreeOpcUa/opcua-asyncio) which also has a [sync-wrapper](https://github.com/FreeOpcUa/opcua-asyncio/blob/master/asyncua/sync.py), with very few changes in API**
