### ISSUE TITLE
client error

### ISSUE THREAD

**Issue by akgaurihar** [FreeOpcUa/python-opcua#622]
we created a server which is running fine but when executing the client code we have certain errors but we feel the code is all right . can anyone take a look of what is wrong in the code attached below .
error messages are showed as follows;
"""""
client connected
Traceback (most recent call last):
  File "C:\Users\student\eclipse-workspace\opcua client\client.py", line 13, in <module>
    Temperature = Temp.get_value()
  File "C:\IP\lib\site-packages\opcua\client\ua_client.py", line 304, in read
    data = self._uasocket.send_request(request)
AttributeError: 'NoneType' object has no attribute 'send_request'

                                                                                                                              """""""""

[client.txt](https://github.com/FreeOpcUa/python-opcua/files/2084604/client.txt)

`[from opcua import Client
import time

url = "opc.tcp://192.168.113.195:5454"

client = Client(url)

client.connect
print("client connected")

while True:
    Temp = client.get_node("ns=2;i=2")
    Temperature = Temp.get_value()
    print(Temperature)
    
    Press = client.get_node("ns=2;i=3")
    Pressure = Press.get_value()
    print(Pressure)
    
    TIME = client.get_node("ns=2;i=4")
    TIME_Value=TIME.get_value()
    print(TIME_Value)
    
    time.sleep(1)
]

**Comment by zerox1212** [comment]
Does it work with UA Expert?

**Comment by akgaurihar** [comment]
server is working on ua expert, but when I run the client code, it is giving me this error

**Comment by akgaurihar** [comment]
Thanks mate ,it worked on removing the get_value!!

**Comment by zerox1212** [comment]
Then you only have the node object. I don't know why `get_value()` gives you a crash, but you could try `get_data_value()` instead.

Be aware, `get_value()` and `get_data_value()` only work on UA nodes of type Variable or Property. Make sure you `Temp` node is really something that has a value.

**Comment by akgaurihar** [comment]
get_data_value did not work too pls find the the screen shots asked for!

![server](https://user-images.githubusercontent.com/34108189/41224167-15b6ce10-6d6c-11e8-93c5-65201a9a0325.PNG)

![client](https://user-images.githubusercontent.com/34108189/41224108-ec362298-6d6b-11e8-8edd-c934485e1dc7.PNG)

![ua expert](https://user-images.githubusercontent.com/34108189/41224086-dcc1760a-6d6b-11e8-84a0-16a946774e08.PNG)

**Comment by oroulet** [comment]
data = self._uasocket.send_request(request)
    AttributeError: 'NoneType' object has no attribute 'send_request'

This is a very very strange error message. Either you try to get the value after the client is down or before.... try to sleep a second before get value. Let me know what happens. In theory it should not change anything, but one should never get that kind of error either...

**Comment by oroulet** [comment]
try also to run your example outside of your editor. Somethime these ~crappy~advanced editor make very strange things in the background

**Comment by akgaurihar** [comment]
It was strange, but  when we rewrote the same code it worked fine!

**Comment by Kog008** [comment]
as far as i am understanding python and its concepts: the __exit__ function is automatically called. So your connection is already gone, when you are trying to close it. U can use the with statement instead: i.e.

with Client(server_url) as opc_client:
        print('Successfully connected opc reader to ', __server_url)
        root = opc_client.get_root_node()
        print("Object node is: ", root)

With this code the __enter__ & __exit__ functions of the Client class are called by default. U can see this by debugging.

**Comment by MariosGkMeng** [comment]
I am facing the same problem here. I would like to add that this particular error happens right after the _uasocket attribute is called:

TIME.server._uasocket.

This expression leads to a "NoneType". 
I reckon that this has to do which a socket-related problem?
