### ISSUE TITLE
utils.ThreadLoop in InternalServer not re-initialized in start⇒stop⇒start scenario

### ISSUE THREAD

**Issue by Nebukadneza** [FreeOpcUa/python-opcua#627]
`InternalServer` creates a `utils.ThreadLoop()` for `asyncio` handling. This `Thread` is started and runs until the server stops. However, if you re-start the server (which is possible / not catched), the `ThreadLoop` object is not re-intialized. This leads to a `RuntimeError: threads can only be started once`, because `ThreadLoop` is-a `Thread`, and threads that exited once cannot be re-started.

To fix this, a new `ThreadLoop` needs to be created when re-starting the server. This new object also needs to be handed to `BinaryServer` again to update its reference, which is still on the old object.

Example of reproducer in IPython:
```
In [1]: import opcua
In [2]: s = opcua.server.server.Server()
In [3]: s.start()
Endpoints other than open requested but private key and certificate are not set.
Listening on 0.0.0.0:4840
### Connected / Disconnected a client here
In [4]: s.stop()
In [5]: s.start()
Endpoints other than open requested but private key and certificate are not set.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-4bb679f43ab8> in <module>()
----> 1 s.start()

~/source/python-opcua/opcua/server/server.py in start(self)
    364         """
    365         self._setup_server_nodes()
--> 366         self.iserver.start()
    367         try:
    368             self.bserver = BinaryServer(self.iserver, self.endpoint.hostname, self.endpoint.port)

~/source/python-opcua/opcua/server/internal_server.py in start(self)
    132         for edp in self.endpoints:
    133             self._known_servers[edp.Server.ApplicationUri] = ServerDesc(edp.Server)
--> 134         self.loop.start()
    135         Node(self.isession, ua.NodeId(ua.ObjectIds.Server_ServerStatus_State)).set_value(0, ua.VariantType.Int32)
    136         Node(self.isession, ua.NodeId(ua.ObjectIds.Server_ServerStatus_StartTime)).set_value(datetime.utcnow())

~/source/python-opcua/opcua/common/utils.py in start(self)
    136     def start(self):
    137         with self._cond:
--> 138             threading.Thread.start(self)
    139             self._cond.wait()
    140 

/usr/lib/python3.6/threading.py in start(self)
    840 
    841         if self._started.is_set():
--> 842             raise RuntimeError("threads can only be started once")
    843         with _active_limbo_lock:
    844             _limbo[self] = self

RuntimeError: threads can only be started once

In [6]:                                                                                                  
```

Finally, the `loop` is currently handed to the `SubscriptionService`, which never uses it — so we can get rid of the additional bogus reference to the object.

I’m opening a PR to fix this.

Thanks — and please tell me if my chain of thought is right ^_^.

**Comment by oroulet** [comment]
Ok. Send or for restart. But I am quite sure the loop is used in InternalSubscription

**Comment by Nebukadneza** [comment]
Hej,

sorry if i mis-read the code — i couldn’t find a reference to being used in SubscriptionService, but if i was worng, i’ll gladly change it so i can also update the loop-reference in SubscriptionService ….

Lets see what travis says ^_^.

**Comment by Nebukadneza** [comment]
… you are right and i am blind. Sorry! I’ll fix this ^_^.

**Comment by Nebukadneza** [comment]
Hi again,

sorry for the fuckup / wasting your time with the last attempt. This looks better IMO. Please let me know what you think ^_^.

Best
-Dario
