### ISSUE TITLE
send a file to server and back to client

### ISSUE THREAD

**Issue by RasPiTool** [FreeOpcUa/python-opcua#635]
Hello, 
Thanks for python-opcua!
I have a fmu-file or zip-file which contians the compiled simulation file.
Now I would like to send this fmu-file or zip-file from PC (Client) to Raspberry PI (Server). 
The Server should unzip the file and execute the simulation.
Unzipping and simulation on Raspberry Pi works fine.
But how can i send the file to the Server and after simulation back to the client?

**Comment by oroulet** [comment]
Either make a ua method or 2 variables of type bytestring. Subscribe to first one on server side, wrote from client, and when new value arrive, simulate then write result in the other variable, etc

**Comment by saimanoj567** [comment]
Can anyone post sample code to access the files from server via opc ua ?

**Comment by AndreasHeine** [comment]
issue is closed!
