### ISSUE TITLE
How to perform remote discovery

### ISSUE THREAD

**Issue by Tenceto** [FreeOpcUa/python-opcua#642]
Hi all, sorry if this question is far too basic, I'm just getting started with OPC and, in particular, with this library.

I'm wondering if it is possible to list all servers that are being hosted in a given IP. As far as I understand, when running the following script:

`from opcua.tools import uadiscover`
`uadiscover()`

The function automatically looks for servers at `127.0.0.1:4840`, the LDS.

Isn't there a way to do this for generic IPs (i.e. connecting to the LDS of the remote host)? Namely, if I want to list all servers in a remote IP instead of `localhost`, how could I do such a task?

**Comment by oroulet** [comment]
As far as I remember you can specify IP address

**Comment by Tenceto** [comment]
How can I do that? When I execute the line `uadiscover()`, it automatically prints:

`Performing discovery at opc.tcp://localhost:4840`

And if I try to pass an IP address to the function, like `uadiscover("192.168.1.5")`, it returns:

`TypeError: uadiscover() takes no arguments (1 given)`

**Comment by oroulet** [comment]
Uadiscover is not meant to be used directly. It is the code of a command line called uadiscover. Look at its code or use the command line
