### ISSUE TITLE
Connection between Server and Client in different places

### ISSUE THREAD

**Issue by RasPiTool** [FreeOpcUa/python-opcua#675]
Hi Guys,
can I connect the client to the server in different places? For example: I start the Raspberry Pi server in City XX and the client is running at my house.
What I've noticed is that the server-client connection works on my local network at home or somewhere else. The server-client connection only works on the local network. When I start the server at home (local network) and the client starts in another network, for example via my neighbor internet, I get an error. The connection failed because the server is not available.

best regards
Max

**Comment by zerox1212** [comment]
OPC UA is TCP based so it works over the internet. If you wanted to host a server on your local connection you need to understand the IT side of it, otherwise your local router will block access. You would need to do port forwarding or put the server in a DMZ.
