### ISSUE TITLE
Is `manage_nodes.delete_nodes` really recursive?

### ISSUE THREAD

**Issue by Nebukadneza** [FreeOpcUa/python-opcua#694]
Hi,

I’ve just looked at the delete_nodes function as it’s also executed by `Server.delete_nodes`. It offers a `recursive` parameter, which i would assume leads to walking all hierarchical children of the nodes specified, and deletes these too. However, that does not seem to be the case:

```
def delete_nodes(server, nodes, recursive=False, delete_target_references=True):                                                                                                                               
    nodestodelete = []                                                                                                                                                                                         
    if recursive:                                                                                                                                                                                              
        nodes += _add_childs(nodes)                                                                                                                                                                            
[…]
def _add_childs(nodes):
    results = []
    for mynode in nodes[:]:
        results += mynode.get_children()
    return results
```

To me, this looks like it’s not recursive, but only deletes the specified nodes as well as their direct children. Childrens children wouldn’t be deleted … right? AFAIK that’s not what the library-user expects when seeing a `recursive=…` parameter.

Thanks nonetheless for this great library ^_^.
Best & Thanks,
-Dario

**Comment by oroulet** [comment]
It is supposed to be recursive... If it does not work open a big report or even better send a PR. It must be a simple error
