### ISSUE TITLE
Client: Problem by writing value to custom server

### ISSUE THREAD

**Issue by destogl** [FreeOpcUa/python-opcua#7]
Hi,

I have problem by writing value in custom server based on UA SDK. I get following error message: The server not does support writing the combination of value, status and timestamps provided.(BadWriteNotSupported). The variable is writeable for sure.

 I found a problem and it is in Timestamps, if the booth timestamp (DataValue structure) are set to 0 than works.

Should the user be enable to set custom Timestamp from client API?

**Comment by oroulet** [comment]
Write a datavalue instead of a variant. Then you have full control. Isn't
it?

**Comment by destogl** [comment]
Yes you are right... Would be than be better to add one more function to node.py with definition:

```
def set_value(self, datavalue)
```

or use directly set_attribute (this is a bit dirty)?

**Comment by oroulet** [comment]
I did not realize that this was an issue with python-opcua!
method overloading is a but messy in python. a method definition with
my_method(*args, **kwargs) messes up documentation.
but in this particula case I think we should modify the method(and the doc
string!!) to support giving a datavalue as argument.
Do you send a patch?
just add
elig isinstance(value, DataValue):
    xxxxx
