### ISSUE TITLE
Use of pycrypto

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#71]
Just grabbed the latest code and noticed https://github.com/FreeOpcUa/python-opcua/commit/dcbc5dda918c9ff1687e158d02d8d03d384fdf3f adds the dependency of pycrypto.

Unfortunately it looks like pycrpto is not supported by Python 3.4+.

Can we make the import of pycrypto only happen if we actually want to use certificates? Otherwise the server can't start with python 3.4 and newer.

The other option is to use a module that is being maintained like https://github.com/Legrandin/pycryptodome
I don't think anyone has updated pycrypto in 2 years?

**Comment by oroulet** [comment]
1) yes i agree pycrypto should be optional
2) are you really sure it does not work for python3.4? It works even for
pypy.....

**Comment by alkor** [comment]
Hmm, pycrypto seems to be in unhealthy state: https://github.com/dlitz/pycrypto/issues/158

**Comment by oroulet** [comment]
Does someone has a better solution? state of crypto i python seems not very good

**Comment by alkor** [comment]
Is https://github.com/pyca/pyopenssl an option? It's a wrapper around openssl library.

Some people recommend using https://github.com/pyca/cryptography , I'll try to read more about it.

**Comment by oroulet** [comment]
you might have found something here @alkor pycripto is not really used as of today, only to sign certificate (works) and encrypt password (broken)

**Comment by oroulet** [comment]
The description of cryptography module looks promising indeed! https://cryptography.io/en/latest/

**Comment by zerox1212** [comment]
Maybe NaCI fits OPC UA better?
https://pynacl.readthedocs.org/en/latest/

**Comment by oroulet** [comment]
just commited a try catch before uacrypto import so it is now possible to run without pycrypto... until we find a better solution

**Comment by oroulet** [comment]
looks like cryptography has everything we need and a much better api than pycrypto, so the choice is quite obvious. It uses somce c code, but that seems to be very little

**Comment by zerox1212** [comment]
Since cryptography looks like a good solution I'll close this issue.
