### ISSUE TITLE
connecting disconnecting frequently causes disconnection to fail

### ISSUE THREAD

**Issue by pinkynrg** [FreeOpcUa/python-opcua#717]
I have the following code:

```
def read(self, node_id):
    start_time = timeit.default_timer()
    try: 
        self.client.connect()
        result = self.client.get_node(node_id)
        value = result.get_value()
        elapsed = timeit.default_timer() - start_time
        log.debug("read method ({}) took {} seconds".format(node_id, elapsed))
        return value
    finally: 
        self.client.disconnect()
```

when I execute this function very fast (~100 times per second), it happened sometimes the finally block has an exception:

```
[Errno 57] Socket is not connected
```

Is this normal?

**Comment by zerox1212** [comment]
It might not be normal, but why would make code like this?

Connect your client once, do all your reads, then disconnect. Why can't you leave the client connected?

**Comment by pinkynrg** [comment]
That's actually what I did now and is (obviously) much faster. 

I guess I made it that way because of distraction.

Thanks!

**Comment by zerox1212** [comment]
If it's a continuous application you can keep the client connected at all times.
