### ISSUE TITLE
How to write a server that DA 2.0 can access?

### ISSUE THREAD

**Issue by tvvbbb** [FreeOpcUa/python-opcua#725]
I had written a server. But I don't know how to connect with DA 2.0 client.

**Comment by oroulet** [comment]
DA is not UA. use google

**Comment by tvvbbb** [comment]
I know it. UA can use an agency to backward compatibility.

**Comment by zerox1212** [comment]
This library only talks UA Binary protocol.

**Comment by tvvbbb** [comment]
Ok. Thank you.
