### ISSUE TITLE
Question: Creating Nodes base on  VariableTypes with properties 

### ISSUE THREAD

**Issue by IzonFreak** [FreeOpcUa/python-opcua#726]
Hello, 

I am trying to import and xml with an information model that contains custom variable types that have properties. I am trying to instantiate this variable types, but I have been unsuccessful. I checked the examples but they are either for custom DataTypes or ObjectTypes. What I am trying to do is as follow: 
```
# Import XML
server.import_xml(\\xmllocation\\model.xml')
###### Do additional server stuff ######
#My VariableType node Id
var_type = ua.NodeId.from_string('ns=2;i=2007')
#If I try this I get  datatype argument must be a nodeid or an int refering to a nodeid
parent.add_variable(idx,'MyVariable', 'default',var_type, ua.VariantType.String)
#If I try this I get AttributeError: 'NodeId' object has no attribute 'name'
parent.add_variable(idx,'MyVariable', 'default',var_type)
```

If I am doing something wrong please let me know.

**Comment by oroulet** [comment]
I do not understand, looks like you are passing wrong type of args. Try to specify argument names in method calls and get type by path do you are the move really exists
