### ISSUE TITLE
How to get value from DataValue?

### ISSUE THREAD

**Issue by AndreGuerra123** [FreeOpcUa/python-opcua#758]
I have the historian function: read_raw_historian()  retrieving a list of DataValue. I can retrieve some attributes such as SourceTimestamp as dv.SourceTimestamp however I need to retrieve the value associated such as a double value. I can do dv.Value but it retrieves a Variant. How to obtain the actual value? Regards

**Comment by brubbel** [comment]
1. dataValue.Value -> variant
2. variant.Value -> your variable.

thus: dataValue.Value.Value

**Comment by AndreGuerra123** [comment]
so simple, yet I would never find it. Closing it. Cheers.
