### ISSUE TITLE
Changing Application URI in client object

### ISSUE THREAD

**Issue by mikelga** [FreeOpcUa/python-opcua#776]
Hello,
I want to use python-opcua as a client to connect to an OPC-UA server (UA CPP Server). I want to communicate using the security configuration Basic256Sha256 and Sign&Encrypt. After using the function 
`client.set_security(getattr(security_policies, 'SecurityPolicy' + 'Basic256Sha256'),"/home/ii40asset/klabeak/Python-opcua client/python_client.der","/home/ii40asset/klabeak/Python-opcua client/python_client_key.pem",mode=ua.MessageSecurityMode.SignAndEncrypt)`

 I see this error in the client: 
`The URI specified in the ApplicationDescription does not match the URI in the certificate.(BadCertificateUriInvalid)` 

On the server after clicking on **Disable ApplicationURI check**, the client works perfectly for me.
But I want to enable again **ApplicationURI check**.

How can I change this ApplicationURI in the client?

Thanks

**Comment by oroulet** [comment]
look at members of client class, there is one called application_uri for example. But I really do not know what your server wants. Write it down in that bug when you find out

**Comment by mikelga** [comment]
Hi, 

I think that I need to write **urn:Mikel-PC:UnifiedAutomation:UaServerCpp** in application_uri. 

I found this in client.py, but I don't know how I can change it:
![image](https://user-images.githubusercontent.com/29535310/50087277-cda5e380-01ff-11e9-83f8-18a7cd46e3ed.png)


This appears in the server features:
![image](https://user-images.githubusercontent.com/29535310/50087094-3a6cae00-01ff-11e9-9930-e3d71431593d.png)

Thank you!

**Comment by zerox1212** [comment]
I think you can just change that attribute.
```python
my_client = Client('some url'0)
my_client.application_uri = "my URI"
```

**Comment by mikelga** [comment]
Thanks! It has worked for me
