### ISSUE TITLE
[Server] method ConditionRefresh implementation 

### ISSUE THREAD

**Issue by maxim-s-barabash** [FreeOpcUa/python-opcua#777]
opcua 0.98.5

Where to look to implement 'ConditionRefresh' method?
Server now returns BadNothingToDo
For test use example examples/client_to_prosys_events.py

**Comment by zerox1212** [comment]
I'm not familiar with this this method, but example code would be helpful. Chances are the UA method isn't implemented.

**Comment by maxim-s-barabash** [comment]
In which module are the UA methods implemented?

**Comment by maxim-s-barabash** [comment]
I myself will try to implement this method.
But I do not find the right place in the code.

**Comment by zerox1212** [comment]
I'm not familiar with this example. If you are using the python client to talk to Prosys and you get this error I think there is a problem with your server, not the client.

**Comment by maxim-s-barabash** [comment]
server, also on python-opcua from examples
