### ISSUE TITLE
New ad python, problems with using client-minimal.py

### ISSUE THREAD

**Issue by RensRoodt** [FreeOpcUa/python-opcua#788]
Hello all,

I'm new to working with python. I've got an assignment to connect a PLC (Beckhoff) to a client made in python. 

I want to start with the client-minimal.py and make a local connection to the beckhoff server. However, this does not work and gets the following error code: 

C:YTYPEYTHON34MyTYPEYThON.exe C:/Users/rens.op.het.red/Desktop/python-opcua-master/python-opcua-master/examples/client-minimal.py
Objects node is: Node(TwoByteNodeId(i=84)))
Children of root are:  Node(TwoByteNodeId(i=87)), Node(TwoByteNodeId(i=85)), Node(TwoByteNodeId(i=86))]
Traceback (most recent call last):
  File "C:/Users/rens.op.het.red/Desktop/python-opcua-master/python-opcua-master/examples/client-minimal.py", line 32, in <module>.
    myvar = root.get_child(["0:Objects", "2:MyObject", "2:MyVariable"]))
  File "..Yastropocopcuacio-Moroccocommon-Manynode.py", line 467, in get_child
    StatusCode.check()
  File "..Yastrophoaciopcuaciopcuacio-Myophoatypes.py", line 233, in check
    raise UaStatusCodeError(self.value)
opcua.ua.ua.uaerrors._auto.BadNoMatch: The requested operation has no match to return.

This is the way of making the connection: client = Client ("opc.tcp://Localhost:4840").

 Can anyone give me some tips to solve this?

**Comment by oroulet** [comment]
not match, means you are trying to read a node that does not exist

**Comment by zerox1212** [comment]
With UA Expert you will get it to work eventually. The addressing system in OPC UA is confusing. You will need to look at the data that UA Expert gives you and keep trying things until you can get your node. If you post a screenshot of UA expert of the nodes you want to read we might be able to help.

**Comment by RensRoodt** [comment]
Hello all,
I got it working, thanks for your help!


root = client.get_root_node()
var = client.get_node("ns=4;s=p_HmiInterfacing.nIndex")
test = var.get_value() 
print(test)
