### ISSUE TITLE
UAExpert error for every event and subscription

### ISSUE THREAD

**Issue by TryToLearn123** [FreeOpcUa/python-opcua#789]
Hi everyone,
I get an error in UAExpert every Time I get an event or subscription notification.
Then I checked the examples if the error also occurs there and it does.
The error seems to have no effect because everything works how it should.
Like it seems that everyone uses the UAExpert certainly someone else already recognized this error and maybe knows the reason for this error.

Here is an screenshot of the error:

![image](https://user-images.githubusercontent.com/38347149/51993782-cedd5800-24af-11e9-915c-2ac173bb33d8.png)

**Comment by zerox1212** [comment]
Is your server using the latest code from master branch?

**Comment by oroulet** [comment]
I have never seen that... Keep it open

**Comment by TryToLearn123** [comment]
I tried it on another system and there it works with no error messages.
So the error has something to do with my system.
Except of the error message everything works fine.
I close the issue.
