### ISSUE TITLE
question set_value usage

### ISSUE THREAD

**Issue by jylilaht** [FreeOpcUa/python-opcua#808]
I have this code where set_value does not work. Get value and connection works. Server I have is some server_example.py or whatsoever. Node I am testing is ns=2;i=3 current value is 1.0

```
myvarnode = client.get_node(nodestring)
value = await myvarnode.get_value()
print("Old value: " + str(value))
print("Input new value: ")
newvalue = input(">> ")
myvarnode.set_value(2.0)
```

Am I missing something here?

**Comment by zerox1212** [comment]
On the server you probably need to `set_writable` or whatever.

**Comment by jylilaht** [comment]
Okay yeah I think I got this sorted out, thank you. I just assumed everything was writable by default but it wasn't the case.
