### ISSUE TITLE
Event subscription to .Net Server

### ISSUE THREAD

**Issue by chranagno** [FreeOpcUa/python-opcua#84]
Hi.
I have a  .Net Opc Ua server which generates events of SystemEventType.
I have managed to subscribe to the events using a .Net client.
However I cannot do the same using the python client (only the data subscription works).
On the other hand the python client works fine with the example python server.
I have used the subscribe_events function with no arguments and subscribe_events(2253,2130)
Am I doing something wrong?
Thanks

**Comment by oroulet** [comment]
it should work but the event system is not very well tested so maybe you
found a bug.
What kind of events do you generate?
I just found å bug and commited a fix in dev2 branch maybe you can try it.

Otherwise you may send me an exe sending events and I can try ut

**Comment by chranagno** [comment]
thanks for the immediate response
I tried the dev2 version with no success.
I want to generate events of a custom type but now I generate SystemType or BaseType events just for testing purposes. 
I'll try to send you an exe tomorrow

**Comment by oroulet** [comment]
what is the status?

**Comment by mertz3hack** [comment]
Is the script supposed to stay open when a data change subscription is started?
When I try to use this it only runs one time before disconnecting. 
There is about a 15second delay time before the data changes again.

**Comment by oroulet** [comment]
no update for while, closing
