### ISSUE TITLE
Time to update tag from kepware server

### ISSUE THREAD

**Issue by faraddouglas** [FreeOpcUa/python-opcua#853]
Hello my friends. It's my first time on guithub. But that's ok. My question:

I am reading 3 tags from kepware server opc. But it takes a long time for a industrial automation. Someone know how to read this tags more fast? I need read 1000 tags at one second.

Sorry for my English. I have studying.

**Comment by oroulet** [comment]
opcua is not fast... if you need speed use ethercat or similar
