### ISSUE TITLE
Issue with decoding Byte type in NodeID

### ISSUE THREAD

**Issue by smith2t** [FreeOpcUa/python-opcua#884]
having issues decoding the following byte to string in python using opcua:
    b'\x00\x00\x00\x00\x01\x00\x00\x00\xd1\x07\x00\x00\x00\x00YtY\x00\x00\x00'
This is an IP21 NodeID. funny thing is that .NET OPCUA clients decode this just fine.
I do know its opaque byte type that basically the app can do what it wants, but am stumped as to how the .NET clients work. I have looked through the source code but haven't seen anything helpful in pointing me to a solution.

**Comment by zerox1212** [comment]
What is the python output? What is supposed to be?

**Comment by smith2t** [comment]
python output is: b'\x00\x00\x00\x00\x01\x00\x00\x00\xd1\x07\x00\x00\x00\x00YtY\x00\x00\x00' which should be like AAAABBBEWEEHHHWWWW as an example. I will try to get the actual and post.

**Comment by oroulet** [comment]
Where do you want the human form to appear?

**Comment by smith2t** [comment]
Need to have human readable form in script output. I’m having issues figuring how to decode byte as it’s form is in known in python.

**Comment by oroulet** [comment]
So what you doing is that you are reading a byte nodeid and want to encode it to utf8? This has nothing to do with opcua. Try mybytes.decode('utf-8') or maybe some windows encoding if that is your world

**Comment by zerox1212** [comment]
I don't really understand where this is happening for you. Do you have an example code of what you are doing? Are you using python-opcua client or server?

**Comment by smith2t** [comment]
That's just it...I don't have the options in the .NET console yet it will resolve the bytes to AAAAAAEAAAAvBgAAAABZdFkAAAA= so it knows some how resolve yet I don't what it should be decoded to and cant find any decode() in python that work. I opened this for help as it looks like the source has a ua_utils.py with some decoding but once invoked it resolved to the byte code in txt.

**Comment by corydodson** [comment]
Below are screenshots from IDLE (python interface) and the OPC UA GUI interface. They are both looking at the same node and providing a different representation of the same node id:
1) python interface: ns=2;b=b'\x00\x00\x00\x00\x01\x00\x00\x00\xd1\x07\x00\x00\x00\x00YtY\x00\x00\x00'
2) GUI interface: ns=2;b=AAAAAAEAAADRBwAAAABZdFkAAAA=

The primary goal is to represent the node id as shown by the GUI from within Python. In other words, get Python to output 2) instead of 1). I have also tried the to_string() method for the node id object within Python, but it just puts double quotes around the text above (pasted here for completeness: "ns=2;b=b'\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\xd1\\x07\\x00\\x00\\x00\\x00YtY\\x00\\x00\\x00'")

![browserClient](https://user-images.githubusercontent.com/34013175/64377241-9eced800-cfef-11e9-835c-a0108455e23f.png)
![idleClient](https://user-images.githubusercontent.com/34013175/64377242-9eced800-cfef-11e9-8b66-f3e022ec4299.png)

**Comment by zerox1212** [comment]
Now I understand. That is interesting that code and GUI are different. @oroulet will probably have insights into this. If I get time I'll dig into it.

**Comment by maxim-s-barabash** [comment]
```
>>> import base64
>>> base64.b64decode("AAAAAAEAAADRBwAAAABZdFkAAAA=")
'\x00\x00\x00\x00\x01\x00\x00\x00\xd1\x07\x00\x00\x00\x00YtY\x00\x00\x00'
```

**Comment by oroulet** [comment]
So that guy had nodeids encoded with base64? It is not an issue, but really nothing related to opcua. Why should we display bytes nodeids as base64? Bytes are bytes

**Comment by maxim-s-barabash** [comment]
opcua not should. I think so. this is a feature of the implementation of the viewer

**Comment by oroulet** [comment]
but why should we decode bytes as base64 on viewer? are all bytes nodeid supposed to be base64?

**Comment by oroulet** [comment]
thinking about it: the .NET viewer probably encode the bytes into base64 to display them, to avoid sending some strange codes to their  display widget. I do not think we have the same issue in python/qt so we have no reasons to encode things to base64

**Comment by smith2t** [comment]
I’m sure the application GUI encoded to base64. I should have tried that. I’m not sure how to pursue this as a bug either. When opaque bytes are allowed it could have been anything. Thanks for the insight on this. I’m going to close this and hopefully will help others if this comes up again in the future.

**Comment by deeTEEcee** [comment]
> but why should we decode bytes as base64 on viewer? are all bytes nodeid supposed to be base64?

Shorter and easier to read than a long series of bytes on the string. Also, the `ns=;b=<bytes>` format will not work right now so that's a bug.

**Comment by dostojewskyi** [comment]
For later joiners. 
IP21 encodes NodeIDs on another base. 
muse the ByteString provided by Aspen and make an base64.decode() use this decoded bytestring for calling get_nodes() which will encode it to hex on the same base.

**Comment by hih4323** [comment]
> For later joiners. IP21 encodes NodeIDs on another base. muse the ByteString provided by Aspen and make an base64.decode() use this decoded bytestring for calling get_nodes() which will encode it to hex on the same base.

Do you have a small code example of this?

Thanks in advance!
