### ISSUE TITLE
Timestamp Timezone

### ISSUE THREAD

**Issue by kevincolyar** [FreeOpcUa/python-opcua#89]
I'm trying to figure out what timezone is being used a server's variables.  There appears to be an hour offset but I'm not sure how to change it.

**Comment by oroulet** [comment]
No idea.. It should be GMT. Do å grep for datetime in opc-ua dir, change
constructors to explicit gmt and send a patch. It would be great

**Comment by kevincolyar** [comment]
According to the docs, `datetime.now()` returns the current local date and time.

https://docs.python.org/2/library/datetime.html#datetime.datetime.now

**Comment by oroulet** [comment]
then find out our to return gmt and send a patch.

**Comment by kevincolyar** [comment]
Working on it... found it might not be an issue.  May be related to issue https://github.com/FreeOpcUa/python-opcua/issues/40 instead.

**Comment by kevincolyar** [comment]
Fixed, see https://github.com/FreeOpcUa/python-opcua/issues/40.
