### ISSUE TITLE
how to use call_method that without arguments

### ISSUE THREAD

**Issue by maomaopenjun** [FreeOpcUa/python-opcua#891]
hello, guys
I am using UAexpert to make a simulation. and I have written a python programm to read the fake data.  this is OK
second, i need to call a method to stop the fake machine
that is the problem 

```
mycondit= myvar.get_child("3:AirConditioner_1")
mycondit.call_method("3: AirConditioner_1.Stop", *args)
```
![image](https://user-images.githubusercontent.com/48068504/65066832-75b22e00-d985-11e9-820b-b01068594bed.png)

as i know,there is no  *args to select or sth.
could you tell me how to do stop method in a right form?

**Comment by oroulet** [comment]
Try with nothing

**Comment by maomaopenjun** [comment]
it did not work...

**Comment by maomaopenjun** [comment]
shall i set the args with VariantType like Int64, Int 32？

**Comment by oroulet** [comment]
if your method does not want any arg then the correct syntax is `        job_id = self.node.call_method(f"{self.ua_idx}:Stop")`. this is taken from a working project
if it takes args, you can set the type if needed

**Comment by maomaopenjun** [comment]
thanks for reply

![image](https://user-images.githubusercontent.com/48068504/65176584-5551a480-da55-11e9-8d80-fa9dfdbf4814.png)
syntax is :
```
mynode = client.get_node("3:AirConditioner_1")
something_stop = mynode.call_method(f"{self.ua_idx}:Stop")
```
what should i write in {**self.ua_idx**}？ 
sorry, I am a new bird

**Comment by tdesroches** [comment]
@maomaopenjun 

I have some functions that don't require args, I used this to call it.
![image](https://user-images.githubusercontent.com/30838946/65878478-28a66280-e35c-11e9-9c5f-7129d1479010.png)
```
# Get Parent Node of Method
sys = client.get_node("ns=16;s=DiagnosisLogbook")

# Get Method Node
method = client.get_node("ns=16;s=DiagnosisLogbook.ClearError")

#Call Method
sys.call_method(method)
```

**Comment by maomaopenjun** [comment]
thx  iwill try
