### ISSUE TITLE
Update Travis CI with Python 3.6+

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/python-opcua#894]
@oroulet I think Travis should be updated to at least Python 3.6. There are some `format` reasons, plus it looks like the current 3.4 is failing while installing `lxml` anyways.

**Comment by zerox1212** [comment]
Appears to be done with https://github.com/FreeOpcUa/python-opcua/pull/899 .

**Comment by oroulet** [comment]
Yes. Thanks for the tips

-------- Original Message --------
