### ISSUE TITLE
Calling Method with an Arg

### ISSUE THREAD

**Issue by tdesroches** [FreeOpcUa/python-opcua#895]
I'm trying to pass an argument to a method.  I was able to call another method that didn't require an argument but I'm not sure how to add the arg.  If someone could give me some pointers I'd appreciate it.

![image](https://user-images.githubusercontent.com/30838946/65798840-b3127a80-e140-11e9-9b59-b2221825a6c9.png)
![image](https://user-images.githubusercontent.com/30838946/65798866-ca516800-e140-11e9-9b18-cab66c2577f3.png)
![image](https://user-images.githubusercontent.com/30838946/65798894-dc330b00-e140-11e9-9371-8f59ea79c883.png)

This is what I'm trying.  uaexpert can call the method with the argument as expected. 
```
sys = client.get_node("ns=18;s=System")
erclr = await sys.get_child("ns=18;s=System.SetTargetMode")
args = ua.Variant([4,])
await sys.call_method(erclr, args)
```
The Response
![image](https://user-images.githubusercontent.com/30838946/65798965-01c01480-e141-11e9-8422-2082c7d41984.png)

I also tried `args = 4`

**Comment by tdesroches** [comment]
When I call the method through uaexpert I get this 
![image](https://user-images.githubusercontent.com/30838946/65877599-10cddf00-e35a-11e9-9ca4-9189c2a5456e.png)

It shows the datatype as "SystemModeEnum", this is a custom datatype.  I think I might need to convert the value to this datatype before passing to the call_method().  After load_type_definitions() I'm not sure how to specify the custom type...

Type Node
![image](https://user-images.githubusercontent.com/30838946/65877993-f6483580-e35a-11e9-8b2d-70cb6b06813d.png)


EnumValues 
![image](https://user-images.githubusercontent.com/30838946/65878037-18da4e80-e35b-11e9-93b2-0ee794e5ce70.png)

**Comment by tdesroches** [comment]
I made a mistake in the code above.  The code I have now is
![image](https://user-images.githubusercontent.com/30838946/66954538-9c1fc380-f02e-11e9-9f51-5ce5d9d8754c.png)
The result
![image](https://user-images.githubusercontent.com/30838946/66954589-b3f74780-f02e-11e9-9829-c94d0ab5c903.png)


I think it may have to do with the variant type...seen above uaExpert calls the data type SystemModeEnum.

**Comment by tdesroches** [comment]
I used the opcua-client-gui, from there I see the arg type is specifed as ns=17;i=3014.  How do I specify a custom datatype?

**Comment by tdesroches** [comment]
Ok Solved.  For those maybe struggling as I have.

Calling a method is easy, especially if it uses native Variant types, however in my case the method I was attempting to call used a custom Variant that was defined on the server.  In order to use this custom Variant I had to get the type node from the server convert it to a variant then use it to define the datatype of my arg when calling the method.

Below is my example, this is a bosch motion controller calling the method to change the controller mode.

```
from opcua import Client, ua
from opcua.common.ua_utils import data_type_to_variant_type

if __name__ == "__main__":
    url = 'opc.tcp://192.168.60.1:4840'
    client = Client(url)
    try:
        client.connect()

        custype = client.get_node("ns=17;i=3014")
        sys = client.get_node("ns=18;s=System")
        Mode = client.get_node("ns=18;s=System.SetTargetMode")
        sys.call_method(Mode, ua.Variant(4, data_type_to_variant_type(custype)))

    finally:
        client.disconnect()
```

**Comment by zerox1212** [comment]
Custom types are annoying. It's a pain to handle systems with many custom types when in most cases the native ones would be just fine.

**Comment by tdesroches** [comment]
Yea it was very frustrating...at the end of the day I sent an integer...
I'm glad I got it, at least if someone struggles with it in the future they can look here.

**Comment by hbszjjw** [comment]
I have a similar problem that I have a custome dataype ScanData which is a Union type as follows:
```
ScanData: Union
  ByteString: ByteString
  String: String
  Epc: ScanDataEpc
  Custom: BaseDataType
```
actually I just need set its value to null in UaExpert, but I don't know how to do it in Python.

**Comment by schroeder-** [comment]
ua.ScanData() = Null

**Comment by schroeder-** [comment]
Sry this only works in Asyncua

**Comment by hbszjjw** [comment]
Sorry, I don't understand, do you mean I should import Asyncua instead of opcua package?
