### ISSUE TITLE
get_value function for getting node values

### ISSUE THREAD

**Issue by EOFFJM** [FreeOpcUa/python-opcua#901]
I would like to know how the get_value function works. Can someone please explain in detail?

**Comment by oroulet** [comment]
Read code? It is just calling opcua read

**Comment by EOFFJM** [comment]
> Read code? It is just calling opcua read

So the client will request the node value to the server, then the server will respond and send that value to client? That is how it works?

**Comment by EOFFJM** [comment]
> Read code? It is just calling opcua read

I read the get_attributes function. I think the client will request the node value to the server, then the server will respond and send that value to client.

**Comment by oroulet** [comment]
exactly. we send opcua "read" message to server
