### ISSUE TITLE
Documentation: "How to generate certificate"

### ISSUE THREAD

**Issue by AndreasHeine** [FreeOpcUa/python-opcua#916]
Hey,

i came across this manual for creating a x509 cert-file:
https://github.com/FreeOpcUa/python-opcua/blob/master/examples/generate_certificate.sh

first of all it will work, but not with all other opc ua stacks out there!
you can test it with UAExpert it marks the missing subAltname/UA Extension (it will work if you ignore it) but... (-_-)°

if you use a x509v3 you will have no trouble with other stacks (HowTo below).

---

**Generate your own Certificate x509v3**
Step 1: Change ssl.conf (subjectAltname, country, organizationName, ...)
Step 2: openssl genrsa -out key.pem 2048
Step 3: openssl req -x509 -days 365 -new -out certificate.pem -key key.pem -config ssl.conf

**ssl.conf:**
[ req ]
default_bits = 2048
default_md = sha256
distinguished_name = subject
req_extensions = req_ext
x509_extensions = req_ext
string_mask = utf8only
prompt = no

[ req_ext ]
basicConstraints = CA:FALSE
nsCertType = client, server
keyUsage = nonRepudiation, digitalSignature, keyEncipherment, dataEncipherment, keyCertSign
extendedKeyUsage= serverAuth, clientAuth
nsComment = "OpenSSL Generated Certificat"
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
subjectAltName = URI:urn:opcua:python:server,IP: 127.0.0.1

[ subject ]
countryName = DE
stateOrProvinceName = HE
localityName = HE
organizationName = AndreasHeine
commonName = PythonOpcUaServer

**Comment by ksrangini05** [comment]
Hi,,I am getting an error "BadCertificateHostNameInvalid"  in UA expert tool while connecting opc server with self signed certificate. In configuration file also, I have added  :  subjectAltName = URI:urn:opcua:python:server,IP: 127.0.0.1, "My company Name" in ssl config. Please someone help on this

**Comment by AndreasHeine** [comment]
python opcua server?

**Comment by ksrangini05** [comment]
yes, python opcua server

**Comment by AndreasHeine** [comment]
is the cert for auth or encryption?

**Comment by ksrangini05** [comment]
- for encryption
- if I want to use the same self signed certificate (from OPENSSL) to connect local host server & cloud server(basically have different IP addresses), how can I add in the config file?

**Comment by AndreasHeine** [comment]
please loock up openssl docs and the x509v3 standard! i will try to reproduce the error but most of the time is a wrong configuration in the cert causing issues

**Comment by AndreasHeine** [comment]
![Unbenannt](https://user-images.githubusercontent.com/56362817/99541560-41833480-29b1-11eb-8e47-89d9a4513aa7.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/56362817/99541564-42b46180-29b1-11eb-811c-6a04d7f67b0f.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/56362817/99541566-43e58e80-29b1-11eb-9952-40bec66ec6fd.PNG)

the code i used no issues... must be your config!
https://github.com/AndreasHeine/SecurePythonOpcUaServer

**Comment by ksrangini05** [comment]
ok,,,thank you

**Comment by admolina19** [comment]
https://github.com/AndreasHeine/SecurePythonOpcUaServer

The repository is down maybe someone could help me I'm trying to replicate but I haven't been successful yet and I have a question, can the certificate be generated this way?

from OpenSSL import crypto, SSL
from opcua import Server, ua
import os

# Genera un par de clave pública / privada
k = crypto.PKey()
k.generate_key(crypto.TYPE_RSA, 2048)

# Crea un certificado autofirmado
cert = crypto.X509()
cert.get_subject().C = "US"
cert.get_subject().ST = "California"
cert.get_subject().L = "San Francisco"
cert.get_subject().O = "My Organization"
cert.get_subject().OU = "My Unit"
cert.get_subject().CN = "localhost"

# Añade el Subject Alternative Name (SAN) con la dirección IP del servidor
san = "IP:0.0.0.0,URI:urn:opcua:testserver"
cert.add_extensions([
    crypto.X509Extension(b"subjectAltName", False, san.encode())
])

cert.set_serial_number(1000)
cert.gmtime_adj_notBefore(0)
cert.gmtime_adj_notAfter(10*365*24*60*60)
cert.set_issuer(cert.get_subject())
cert.set_pubkey(k)
cert.sign(k, 'sha256')

# Configura el certificado y la clave privada en el servidor OPC UA
server = Server()
server.set_endpoint("opc.tcp://0.0.0.0:4840/testserver")
server.set_security_policy([ua.SecurityPolicyType.Basic256Sha256_SignAndEncrypt])
server.certificate = crypto.dump_certificate(crypto.FILETYPE_PEM, cert)
server.private_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, k)

# Guarda el certificado en un archivo PEM
with open("certV2.der", "wb") as f:
    f.write(crypto.dump_certificate(crypto.FILETYPE_ASN1, cert))

# Guarda la clave privada en un archivo PEM
with open("keyV2.pem", "wb") as f:
    f.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, k))

# Obtener el directorio actual
cwd = os.getcwd()

# Imprimir la ruta completa de los archivos
print(os.path.join(cwd, "certV2.pem"))
print(os.path.join(cwd, "keyV2.pem"))

**Comment by schroeder-** [comment]
san = "URI:urn:opcua:testserver, IP:0.0.0.0"
As of spec san must begin with uri of the server.
Also you din't set the server urn to match san.
