### ISSUE TITLE
SendBufferSize vs ReceiveBufferSize

### ISSUE THREAD

**Issue by brubbel** [FreeOpcUa/python-opcua#943]
https://github.com/FreeOpcUa/python-opcua/blob/ec188d15072f39602ba1f977a2ea97fd4de8b513/opcua/common/connection.py#L340-L343

When the client receives an ACK message from the server, it stores the ACK.SendBufferSize as _max_chunk_size (used to chunk messages the client sends to the server.)
However, SendBufferSize is the maximum message size the server will send to the client.
https://reference.opcfoundation.org/v104/Core/docs/Part6/7.1.2/#7.1.2.4

So, instead this should be `self._max_chunk_size = msg.ReceiveBufferSize`

**Comment by oroulet** [comment]
Sounds like a big error ;-) thanks

**Comment by oroulet** [comment]
It looks like the entire chunk code must be check. We also sometimes get strange errors from that code complaining about wrong sequence

**Comment by brubbel** [comment]
Reading carefully, it seems that the current code is correct. The client sends a Hello + SendBufferSize1 to the server, which replies with an ACK + SendBufferSize2 <= SendBufferSize1. Then the client sets this SendBufferSize2 as the maximum TX size.
(If I understand correctly the SendBufferSize and ReceiveBufferSize are symmetrical for client and server, but they first negotiate the maximum values)
