### ISSUE TITLE
Read raw history breaks if no server implementation

### ISSUE THREAD

**Issue by luisfmelo** [FreeOpcUa/python-opcua#949]
When I apply the function `node.read_raw_history(...)`, if the server-side history functionality is not implemented, it is raising an exception: 

`{AttributeError}'NoneType' object has no attribute 'DataValues'`

This is because this line: `result = self.history_read(details)` returns status code 'BadHistoryOperationUnsupported'.

We should, in my opinion, raise a more verbose exception instead of that `AttributeError`

I'm currently working on a fix.

**Comment by oroulet** [comment]
thanks
