### ISSUE TITLE
How to set identifierType as string in nodeId?

### ISSUE THREAD

**Issue by jadhavshital** [FreeOpcUa/python-opcua#952]
Hi,
I need to set nodeId with identifierType as string (for e.g. nodeId : "ns=2;s=counter1").
By default this library sets nodeId as numeric type (for e.g. "ns=2;i=2")

Can anyone help me?
Thanks is advance.

**Comment by brubbel** [comment]
You can find some inspiration here:
https://github.com/FreeOpcUa/python-opcua/blob/1c73bb8ab9c03987a4900c7515c25acf1d6d8597/tests/tests_common.py#L348-L354

**Comment by jadhavshital** [comment]
@brubbel It worked. Thank you so much.
