### ISSUE TITLE
Cannot connect to remote OPC server: [WinError 10061]

### ISSUE THREAD

**Issue by smjure** [FreeOpcUa/python-opcua#969]
First of all thank you for doing such a great work.

I am trying to connect to remote OPC server. I have its Host name, Server ID, Server IP. The firewall was disconnected - all ports are opened. I tried:
```
from opcua import Client
client = Client("opc.tcp://192.168.0.50:55101") 
client.connect()
```
also
```
client = Client("opc.tcp://192.168.0.50:55101/ServerID") 
client.connect() 
```
and similar things and always get the following error:

> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

When I try with UaExpert, I get the following error:

> [uastack] OpcUa_SecureConnection_OnNotify: Connect event: ERROR 0x80050000!
> [uastack] OpcUa_SecureConnection_OnNotify: Connect event: Notifying owner! 0x80050000
> Could not connect to server: BadCommunicationError

On the other hand, I can easily connect with Siemens and Matlab OPC clients just by providing Host name and Server name.

Any comments or suggestions appreciated   (?)

**Comment by oroulet** [comment]
Sounds like an opc da and NOT an opca ua server

**Comment by smjure** [comment]
Ture, it is OPC DA server. Is there any other way to establish the connection?

**Comment by brubbel** [comment]
https://github.com/FreeOpcUa/python-opcua/issues/489

**Comment by smjure** [comment]
@brubbel Thank you, that worked. I'd just give a couscous reminder for future addressee to be careful about dependencies and their versions, it will save you a lot of time.

**Comment by LonelySadhu** [comment]
What could it be?
 raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: OpenOPC.OPCError
