### ISSUE TITLE
How to catch exceptions such as ServiceFault...

### ISSUE THREAD

**Issue by Take44** [FreeOpcUa/python-opcua#992]
When the server side is really stopped by shutdown etc., Please tell me how to catch exceptions such as ServiceFault on the client side.

**Comment by AndreasHeine** [comment]
You can run a second connection with a cyclic read of the servicelevel node if it throws a exception you know the server is off or you can just try to connect and disconnect to the server from a different thread. If the server is not responding thats the only way to find out...

**Comment by Take44** [comment]
I'll try your advice.
Thank you.

**Comment by oroulet** [comment]
Do not use a second connection. But use a thread or simply read some nodes every second or similar
